var arrLang = {
    "en": {
        "LANG_HORIZONTAL" : "Horizontal",
        "LANG_VERTICAL" : "Vertical",
        "LANG_MENU_LAYOUT_SELECT" : "Menu Layout Select",
        "LANG_FAMILY_GROUP_MANAGEMENT" : "Parental Control",
        "IPERF_TEST_INSTRUCTION1" : "With the software 'Magic iPerf' for wlan basic speed measurement",
        "IPERF_TEST_INSTRUCTION2" : "Select an online device and click Start",
        "IPERF_TEST_INSTRUCTION3" : "1. 'Magic iPerf' Run the 'iperf3 -c [gateway ip] -i 1' command to test the uplink rate",
        "IPERF_TEST_INSTRUCTION4" : "2. 'Magic iPerf' Run the 'iperf3 -s -i 1' command to test the downlink rate",
        "LANG_STATIC_ROUTE_TIPS2" : "Please select an available WAN interface",
        "LANG_STATIC_ROUTE_TIPS" : "At least one WAN is available to configure static routes",
        "LANG_DMZ_TIPS" : "DMZ ip should be on the same network segment as lan ip (and different from lan ip)",
        "LANG_MAC_FILTER_ADD_TIPS": "After the list is modified, it's needed to submit mac address filter again to take effect.",
        "LANG_SUBMIT_FAIL" : "Submit Fail",
        "LANG_MAC_FILTER": "Mac Filter",
        "LANG_UPDATE": "Update",
        "LANG_WRIELESS_PERFORMANCE": "Wireless Performance Status",
        "LANG_CAP_TYPE": "Capture type",
        "LANG_MANAGE_FRAME": "Management Frame",
        "LANG_WLAN_FRAME_CAP": "WLAN Frame Capture",
        "LANG_PON_AUTH_LOG": "Pon Debug Status",
        "LANG_PON_AUTH_LOG_TIPS1": "The Pon process will output debug msg to the serial log",
        "LANG_PON_AUTH_LOG_TIPS2": "Enabling Pon Debug affects system performance.",
        "LANG_PON_AUTH_LOG_TIPS3": "Disable Pon Debug when it is not needed",
        "LANG_CLEAR_SERIAL_LOG": "Clear Serial Log",
        "LANG_SERIAL_LOG": "Serial Log Download",
        "LANG_CATV_STATUS": "CATV Status",
        "LANG_SYNC": "Sync",
        "LANG_UPTIME": "Uptime",
        "LANG_WEB_UPTIME":"Tempo de atividade",
        "LANG_PPPOE_UPTIME": "PPPoE Uptime",
        "LANG_STRRSSITHRESHOLD": "Error! Invalid value of RSSI threshold",
        "LANG_RSSI_THRESHOLD": "Associate RSSI Threshold",
        "LANG_RM_RSSI_THRESHOLD": "Remove RSSI Threshold",
        "LANG_WIRELESS_PERFORMANCE": "Wireless Performance",
        "LANG_WLAN_SCHEDULE_FROM": "From",
        "LANG_WLAN_SCHEDULE_TO": "To",
        "LANG_WLAN_SCHEDULE_FOR_HOUR": "(h)",
        "LANG_WLAN_SCHEDULE_FOR_MIN": "(m)",
        "LANG_CONNECTED_TIME": "Connected time",
        "LANG_CLI_TIMING_FUNC_TIPS": "This function needs to turn on the SNTP update function in the time setting, and it can be used after the synchronization is successful.",
        "LANG_RATE_LIMIT_TIPS": "Rate limit unit: KB/s, 0 is unlimit.",
        "LANG_UPLOAD_LIMIT": "Upload rate limit",
        "LANG_DOWNLOAD_LIMIT": "Download rate limit",
        "LANG_NOT_SURFING_INTERNET": "No surfing the Internet",
        "LANG_USE_TIME_LIMIT": "Use time limit",
        "LANG_START_END_NOT_BE_SAME": "The start time and the end time cannot be the same",
        "LANG_NEED_INTEGER_IN_RANGE": "Please enter an integer in the range",
        "LANG_WLAN_CLIENT_MANGEMENT": "Wifi Client",
        "LANG_ADVANCE_MQTT_CONFIG": "MQTT Config",
        "CAPUTURE_INSTRUCTION1": "Count mode: automatically stops when the number of packets reaches 5000",
        "CAPUTURE_INSTRUCTION2": "Rotate mode: rotates the  dump file. Capture size: 3MB ~ 6MB",
        "CAPUTURE_INSTRUCTION3": "When the interface is Any, the data on the LAN side will also be captured",
        "EXECUTE_REPAIR": "Execute Repair",
        "LANG_CHOOSE_A_INTERFACE": "Please choose a interface",
        "LANG_DOWNLOAD_CAPTURE_FILE": "Download Capture File",
        "LANG_ROTATE": "Rotate",
        "LANG_COUNT": "Count",
        "LANG_CAPTURE_MODE": "Capture Mode",
        "LANG_CAPTURE_PACKETS_ON_WAN": "Capture Packets on WAN",
        "PPPoE_DIAG": "PPPoE Service Diagnosis",
        "DHCP_DIAG": "DHCP Service Diagnosis",
        "LAN_CONFIG_DIAG": "LAN Config Diagnosis",
        "INTERNET_CONNECT_DIAG": "Internet Connectivity Diagnosis",
        "WAN_PARAMS_DIAG": "WAN Config Diagnosis",
        "PON_DIAG": "PON Diagnosis",
        "SYS_STATUS_DIAG": "System Status Diagnosis",
        "WAN_CONNECT_DIAG": "Wan Connect Status Diagnosis",
        "PORT_DIAG": "Port Diagnosis",
        "ROUTE_DIAG": "Route Diagnosis",
        "LANG_SELF_DIAGNOSE": "Self-diagnosis",
        "HGU Config": "HGU Config",
        "LANG_BASIC_SETTINGS": "Basic Settings",
        "LANG_STATUS": "Status",
        "HGU Status": "HGU Status",
        "LANG_DEVICE_INFO": "Device Info",
        "LANG_WAN_CONNECTION_INFO": "WAN Info",
        "PON_INFO": "PON Info",
        "LANG_USER_INFO": "User Info",
        "LANG_WLAN_SURVERY_INFO": "Wlan Survery Info",
        "LANG_NETWORK": "Network",
        "Network Settings": "Network Settings",
        "LANG_WAN": "WAN",
        "LANG_LAN": "LAN",
        "LANG_WLAN": "WLAN",
        "Others": "Others",
        "LANG_BIND": "Binding",
        "LANG_TR069": "TR069",
        "LANG_QOS": "QoS",
        "LANG_TIME": "Time",
        "LANG_ROUTER_CONFIG": "Route",
        "Advance Settings": "Advance Settings",
        "LANG_SECURITY": "Security",
        "Security Config": "Security Config",
        "LANG_WAN_ACCESS_CONFIG": "WAN Access",
        "LANG_FIREWALL": "Firewall",
        "LANG_MAC_FILTERING": "MAC Filtering",
        "LANG_IP_PORT_FILTERING": "IP/Port Filtering",
        "LANG_APPLICATION": "Application",
        "Application Config": "Application Config",
        "LANG_VOIP": "VoIP",
        "Multicast Setting": "Multicast Setting",
        "LANG_ADVANCE_NAT_CONFIG": "Advance NAT",
        "LANG_MANAGEMENT": "Management",
        "LANG_USER_MANAGEMENT": "User Manage",
        "LANG_DEVICE_MANAGEMENT": "Device Manage",
        "LANG_LOG_FILE_MANAGEMENT": "Log Manage",
        "LANG_DIAGNOSTICS": "Diagnostics",
        "Diagnose Tools": "Diagnose Tools",
        "LANG_NETWORK_DIAGNOSTICS": "Network Diagnostics",
        "LANG_LOOPBACK_SET": "Loopback Test",
        "LANG_HELP": "Help",
        "Help Information": "Help Information",
        "About Network": "About Network",
        "About Application": "About Application",
        "Search": "Search",
        "LANG_LOGOUT": "Logout",
        "IPv4 LAN Configuration": "IPv4 LAN Configuration",
        "LANG_TIP_ADDR": "IP Address",
        "LANG_SUBNET_MASK": "Subnet Mask",
        "Enable DHCP Server": "Enable DHCP Server",
        "Start IP Address": "Start IP Address",
        "End IP Address": "End IP Address",
        "LANG_LEASE_TIME": "Lease Time",
        "LANG_ONE_WEEK": "One Week",
        "LANG_ONE_MINUTE": "One Minute",
        "LANG_ONE_HOUR": "One Hour",
        "LANG_ONE_DAY": "One Day",
        "LAN DNS Mode": "LAN DNS Mode",
        "Primary IP DNS": "Primary IP DNS",
        "Secondary IP DNS": "Secondary IP DNS",
        "Enable DHCP Server Relay": "Enable DHCP Server Relay",
        "DHCP Server IP": "DHCP Server IP",
        "wan_submit": "Submit",
        "LANG_RESERVE_IP_ADDRESS_LIST": "Reserve IP Address List",
        "LANG_ADD": "Add",
        "IPv6 LAN Configuration": "IPv6 LAN Configuration",
        "LANG_IPV6_ADDRESS": "IPv6 Address",
        "IPv6 LAN DNS Mode": "IPv6 LAN DNS Mode",
        "LANG_INTERFACE": "Interface",
        "Primary IPv6 DNS": "Primary IPv6 DNS",
        "Secondary IPv6 DNS": "Secondary IPv6 DNS",
        "LAN Prefix Delegation": "LAN Prefix Delegation",
        "IPv6 Prefix : (2001::/64)": "IPv6 Prefix (2001::/64)",
        "LANG_DHCPV6": "DHCPv6",
        "DHCPv6 Mode": "DHCPv6 Mode",
        "Start IP Address(IPv6)": "Start IP Address (IPv6)",
        "End IP Address(IPv6)": "End IP Address (IPv6)",
        "LANG_VALID_LIFETIME": "Valid Lifetime",
        "LANG_PREFERRED_LIFETIME": "Preferred Lifetime",
        "RA Configuration": "RA Configuration",
        "RA Enable": "RA Enable",
        "LANG_ADVMANAGEDFLAG": "Adv Managed Flag",
        "LANG_ADVOTHERCONFIGFLAG": "Adv OtherConfig Flag",
        "LANG_MAXRTRADVINTERVAL": "Max RtrAdv Interval",
        "LANG_MINRTRADVINTERVAL": "Min RtrAdv Interval",
        "LANG_DEVICE_BASIC_INFO": "Device Basic Info",
        "LANG_DEVICE_MODEL": "Device model",
        "LANG_DEVICE_SN": "Device SN",
	     	"LANG_DEVICE_ID": "Device ID",
        "LANG_DEVICE_RESOURCE_INFO": "Resource Info",
        "LANG_DEVICE_CPUSAGE": "CPU Usage",
        "LANG_DEVICE_MEMUSAGE": "Memory Usage",
        "LANG_HARDWARE_VERSION": "Hardware Version",
        "LANG_FIRMWARE_VERSION": "Firmware Version",
        "LANG_SERIAL_NO": "PON S/N",
        "IPv4 WAN Info": "IPv4 WAN Info",
        "LANG_SRV_INTF": "Service Interface",
        "LANG_VLAN_ID": "VLAN ID",
        "LANG_PROTOCOL": "Protocol",
        "LANG_IGMP_CONFIG": "IGMP",
        "LANG_IP_ADDRESS": "IP Address",
        "LANG_MAC_ADDRESS": "MAC Address",
        "IPv4 Network Info": "IPv4 Network Info",
        "LANG_DEFAULT_GATEWAY": "Default Gateway",
        "LANG_DNS_FIRST": "Primary DNS",
        "LANG_DNS_SECOND": "Standby DNS",
        "LANG_PREFIX": "Prefix",
        "LANG_REMOTE_MANAGEMENT_INFO": "Remote Manage Info",
        "LANG_TR069_INFO_ADMIN": "Connection",
        "LANG_TR069_CONNECT_REQUEST_STATE": "ACS connect request state",
        "LANG_TR069_SERVICE_CONFIG_STATE": "ACS config state",
        "LANG_VOIP_INFO": "Voip Info",
        "LANG_PORT_STATE": "Port State",
        "LANG_PHONE_NUMBER": "Phone Number",
        "LANG_ENABLE": "Enable",
        "LANG_DISABLE": "Disable",
        "LANG_NO_INFORM": "no inform",
        "LANG_NO_RESPONSE": "inform no response",
        "LANG_INFORM_BREAK": "inform break",
        "LANG_INFORM_SUCCESS": "inform success",
        "LANG_INFORM_AUTH_FAIL": "inform auth fail",
        "LANG_INFORMING": "informing",
        "LANG_NONE": "NONE",
        "LANG_TR069_NO_REQUEST": "ACS no request",
        "LANG_TR069_REQUEST_BREAK": "ACS request break",
        "LANG_TR069_REQUEST_SUCCESS": "ACS request success",
        "LANG_TR069_NO_SET": "ACS not set",
        "LANG_TR069_SETTING": "ACS setting ",
        "LANG_TR069_SET_SUCCESS": "ACS set success",
        "LANG_TR069_SET_FAULT": "ACS set fault",
        "LANG_NET_CONNECT_INFO": "Connect information",
        "LANG_NET_CONNECT_STATE": "Connect state",
        "LANG_FEC_CAPACITY": "FEC Capacity",
        "LANG_SUPPORT": "Support",
        "LANG_FEC_UPSTREAM_STATUS": "FEC Upstream Status",
        "LANG_FEC_DOWNSTREAM_STATUS": "FEC Downstream Status",
        "LANG_ENCRYPT_MODE": "Encrypt Mode",
        "LANG_LASER_DEVICE_INFO": "Laser Device Info",
        "LANG_TX_POWER": "Tx Power",
        "LANG_RX_POWER": "Rx Power",
        "LANG_TEMPERATURE": "Temperature",
        "LANG_VOLTAGE": "Voltage",
        "LANG_BIAS_CURRENT": "Bias Current",
        "LANG_EPON_ALARM_INFO": "PON Alarm Info",
        "LANG_LINK_PERFORMANCE_INFO": "Link Performance Info",
        "LANG_TX_BYTE": "Tx Bytes",
        "LANG_RX_BYTE": "Rx Bytes",
        "LANG_TX_FRAME": "Tx Frame",
        "LANG_RX_FRAME": "Rx Frame",
        "LANG_TX_UNICAST_FRAME": "Tx Unicast Frame",
        "LANG_RX_UNICAST_FRAME": "Rx Unicast Frame",
        "LANG_TX_MULTICAST_FRAME": "Tx Multicast Frame",
        "LANG_RX_MULTICAST_FRAME": "Rx Multicast Frame",
        "LANG_TX_BROADCAST_FRAME": "Tx Broadcast Frame",
        "LANG_RX_BROADCAST_FRAME": "Rx Broadcast Frame",
        "LANG_RX_FEC_ERR_FRAME": "Rx FEC Error Frame",
        "LANG_RX_HEC_ERR_FRAME": "Rx HEC Error Frame",
        "LANG_TX_LOSE_FRAME": "Tx Lose Frame",
        "LANG_TX_PAUSE_STREAM_CONTROL_FRAME": "Tx PAUSE Control Frame",
        "LANG_RX_PAUSE_STREAM_CONTROL_FRAME": "Rx PAUSE Control Frame",
        "LANG_NOT_RESISTERED_NOT_AUTHED": "Not registered,Not certificated",
        "LANG_RESISTERED_NOT_AUTHED": "Registered,Not certificated",
        "LANG_RESISTERED_AUTHED": "Registered,Certificated",
        "WLAN Interface": "WLAN Interface",
        "WLAN Site Survey": "WLAN Site Survey",
        "SSID-Name": "SSID-Name",
        "SSID Hide": "SSID Hide",
        "LANG_ENCRYPTION": "Encryption",
        "LANG_CHANNEL": "Channel",
        "LANG_FLAG": "Flag",
        "LANG_MODE": "Mode",
        "LANG_ASSOCIATED_CLIENTS": "Associated Clients",
        "LANG_TX_PKT": "Tx pkt",
        "LANG_RX_PKT": "Rx pkt",
        "Send Rate (Mbps)": "Send Rate (Mbps)",
        "RSSI (dBm)": "RSSI (dBm)",
        "LANG_POWER_SAVING": "Power Saving",
        "LANG_EXPIRED_TIME_SEC": "Expired Time (sec)",
        "WLAN Send and Recv": "WLAN Send and Recv",
        "Packets (Recv)": "Packets (Recv)",
        "Bytes (Recv)": "Bytes (Recv)",
        "Errors (Recv)": "Errors (Recv)",
        "Dropped (Recv)": "Dropped (Recv)",
        "Packets (Send)": "Packets (Send)",
        "Bytes (Send)": "Bytes (Send)",
        "Errors (Send)": "Errors (Send)",
        "Dropped (Send)": "Dropped (Send)",
        "LAN Interface": "LAN Interface",
        "LAN Send and Recv": "LAN Send and Recv",
		    "LAN Status": "LAN Status",
        "LANG_ACTIVE_DHCP_CLIENTS": "Active DHCP Clients",
        "LANG_DEVICE_TYPE": "Device Type",
        "LANG_MESH_NEI_MAC": "MAC Address",
        "WAN Configuration": "WAN Configuration",
        "LANG_CONNECTION_NAME": "Connectin Name",
        "LANG_ADD_NEW_WAN_LINK": "Add New Wan",
        "LANG_IP_VERSION": "IP Version",
        "Connection Mode:": "Connection Mode",
        "LANG_ENABLE_VLAN": "Enable VLAN",
        "LANG_VLAN_ID_TITLE": "VLAN ID",
        "pppoe_username": "Username",
        "pppoe_password": "Password",
        "pppoe_service_name": "Service Name",
        "pppoe_ppptype": "PPP Type",
        "pppoe_continuous": "Continuous",
        "pppoe_connect_on_demand": "Connect on Demand",
        "LANG_MESH_NEI_IP": "IP Address",
        "Service Mode:": "Service Mode",
        "Disable LAN DHCP:": "Disable LAN DHCP",
        "binding port": "Binding Port",
        "port_binding_select": "Port Selection",
        "port_1": "LAN_1",
        "port_2": "LAN_2",
        "port_3": "LAN_3",
        "port_4": "LAN_4",
        "wireless(ssid1-5g)": "WLAN (AP0-5G)",
        "wireless(ssid2-5g)": "WLAN (AP1-5G)",
        "wireless(ssid3-5g)": "WLAN (AP2-5G)",
        "wireless(ssid4-5g)": "WLAN (AP3-5G)",
        "wireless(ssid5-2.4g)": "WLAN (AP0-2.4G)",
        "wireless(ssid6-2.4g)": "WLAN (AP1-2.4G)",
        "wireless(ssid7-2.4g)": "WLAN (AP2-2.4G)",
        "wireless(ssid8-2.4g)": "WLAN (AP3-2.4G)",
        "wan_ipv6_address_mode": "WAN IPv6 Address Mode",
        "global_ipv6_mode": "Global IPv6 Mode",
        "LANG_STAT_LESS": "Stateless",
        "LANG_MANUAL": "Manual",
        "ipv6_dhcp": "DHCP",
        "dhcp_enable_prefix_proxy": "DHCP Enable Prefix Proxy",
        "ds-lite-enable": "DS-Lite Enable",
        "AFTR Address Mode": "AFTR Address Mode",
        "AFTR Address_Domain": "AFTR Address/Domain",
        "ipv6_ip_address": "IPv6 IP Address",
        "ipv6_gateway": "IPv6 Gateway",
        "ipv6_request_dns": "Request DNSv6",
        "ipv6_primary_dns": "Primary DNS",
        "ipv6_secondary_dns": "Secondary DNS",
        "wan_del": "Delete",
        "LANG_NAT_CONFIG": "NAT Config",
        "2.4g Wlan Basic Setting": "2.4G WLAN Basic Setting",
        "LANG_DISABLE_WLAN_INTERFACE": "Disable WLAN Interface",
        "LANG_BAND": "Band",
        "LANG_SSID": "SSID",
        "LANG_CANCEL_BROADCAST": "Cancel Broadcast",
        "LANG_BLOCK_RELAY": "Block Relay",
        "LANG_WMM_SUPPORT": "WMM Support",
        "LANG_POWER_ENHANCING": "Power Enhancing",
        "LANG_CHANNEL_WIDTH": "Channel Width",
        "LANG_CONTROL_SIDEBAND": "Control Sideband",
        "LANG_CHANNEL_NUMBER": "Channel Number",
        "LANG_AUTO": "Auto",
        "LANG_AUTO_WITH_DFS": "Auto (DFS)",
        "LANG_AUTO_WITHOUT_DFS": "Auto (Without DFS)",
        "LANG_RADIO_POWER": "Radio Power (%)",
        "LANG_REGDOMAIN": "Regdomain",
        "LANG_WPS": "WPS",
        "LANG_AUTHENTICATION": "Authentication",
        "LANG_OPEN_SYSTEM": "Open System",
        "LANG_SHARED_KEY": "Shared Key",
        "LANG_KEY_LENGTH": "Key Length",
        "LANG_KEY_FORMAT": "Key Format",
        "LANG_ENCRYPTION_KEY": "Encryption Key",
        "LANG_AUTHENTICATION_MODE": "Authentication Mode",
        "LANG_IEEE_802_11W": "IEEE 802.11w",
        "LANG_SHA256": "SHA256",
        "WPA Cipher Suite": "WPA Cipher Suite",
        "WPA2 Cipher Suite": "WPA2 Cipher Suite",
        "LANG_GROUP_KEY_UPDATE_TIMER": "Group Key Update Timer",
        "LANG_PRE_SHARED_KEY_FORMAT": "Pre-Shared Key Format",
        "LANG_PRE_SHARED_KEY": "Pre-Shared Key",
        "RADIUS Server IP Address": "RADIUS Server IP Address",
        "RADIUS Server Port": "RADIUS Server Port",
        "RADIUS Server Password": "RADIUS Server Password",
        "LANG_ADVANCED": "Advanced",
        "LANG_WLAN_MULTIPLE_BSSID_SETTINGS": "WLAN Multiple BSSID Settings",
        "5g Wlan Basic Setting": "5G WLAN Basic Setting",
        "LANG_WI_FI_PROTECTED_SETUP": "WPS Settings",
        "LANG_DISABLE_WPS": "Disable WPS",
        "LANG_SELF_PIN_NUMBER": "Self PIN Number",
        "LANG_START_PBC": "Start PBC",
        "LANG_CLIENT_PIN_NUMBER": "Client PIN Number",
        "LANG_START_PIN": "Start PIN",
        "LANG_LOGIN": "Login",
        "LANG_USERNAME": "Username",
        "LANG_PASSWORD": "Password",
        "enter verification code": "Enter captcha",
        "wrong user name or password": "wrong user name or password",
        "VERIFICATION_CODE_IS_NOT_CORRECT_PLEASE_INPUT_THE_PROPER_VERIFICATION_CODE": "ERROR: Verification code is not correct! please input the proper verification code!",
        "LANG_LOGIN_ERROR_3": "ERROR:You have entered wrong username or password thrice, Please wait a while before reloging !",
        "LANG_LOGIN_ERROR_4": "ERROR:another user have logined in using this account!only one user can login using this account at the same time.",
        "LANG_LOGIN_ERROR_5": "ERROR:you have logined! please logout at first and then login!",
        "LANG_LOGIN_ERROR_6": "ERROR:web authentication error!please close this window and reopen your web browser to login!",
        "LANG_FIRMWARE_UPGRADE": "Upgrade Image",
        "LANG_PAGE_DESC_UPGRADE_FIRMWARE": "This page allows you upgrade the firmware to the newer version. Please note that do not power off the device during the upload because this make the system unbootable.",
        "LANG_CHOOSE_FILE": "Choose File",
        "LANG_UPGRADE": "Upgrade",
        "LANG_RESET": "Reset",
        "LANG_SELECTED_FILE_CANNOT_BE_EMPTY": "Selected file cannot be empty!",
        "LANG_CANCEL": "Cancel",
        "LANG_PAGE_DESC_UPGRADE_CONFIRM": "Do you really want to upgrade the firmware?",
        "LANG_UPGRADE_FAIL_REASON_3": "invalid file",
        "LANG_UPGRADE_FAIL_REASON_1": "file too large",
        "LANG_UPGRADE_FAIL_REASON_2": "invalid file",
        "LANG_DEVICE_RESETTING": "Device Resetting, please wait ...",
        "UPLOAD_MODEL_IMAGE_FILE_ERROR": "The device model corresponding to the upgrade file is incorrect",
        "UPLOAD_VENDOR_IMAGE_FILE_ERROR": "The device vendor corresponding to the upgrade file is incorrect",
        "UPLOAD_PONLOCK_IMAGE_FILE_ERROR": "The pon lock corresponding to the upgrade file is incorrect",
        "UPLOAD_DEFAULT_IMAGE_FILE_ERROR": "Incorrect upgrade file",
        "Upgrade_Success": "Upgrade Success!",
        "LANG_UPLOAD_FAILED": "Upload failed",
        "LANG_INACTIVE": "Inactive",
        "LANG_NOT_REGISTERED": "Not Registered",
        "LANG_REGISTERED": "Registered",
        "LANG_REGISTERING": "Registering",
        "LANG_REGISTER_FAIL": "Register Fail",
        "LANG_VOIP_RESTART": "VoIP Restart...",
        "LANG_ERROR": "ERROR",
        "LANG_OFF_HOOK": "Off Hook",
        "LANG_DAIL": "Dailing",
        "LANG_RINGING": "Ring",
        "LANG_RINGBACK": "Ring Back",
        "LANG_CALL_CONNECTED": "Call Connected",
        "LANG_REGISTER_FAI": "Register failed",
        "LANG_COMMIT_REBOOT": "Commit/Reboot",
        "LANG_COMMIT_AND_REBOOT": "Commit and Reboot",
        "LANG_AUTO_REBOOT": "Timely Reboot",
        "LANG_CURRENT_TIME": "Current Time",
        "LANG_SUN": "Sun",
        "LANG_MON": "Mon",
        "LANG_TUE": "Tue",
        "LANG_WED": "Wed",
        "LANG_THU": "Thu",
        "LANG_FRI": "Fri",
        "LANG_SAT": "Sat",
        "LANG_SYS_SCH_DAY": "Week Day",
        "LANG_SYS_SCH_TIME": "Time",
        "LANG_HOUR": "Hour",
        "LANG_MIN": "Min",
        "LANG_SYNCHRONIZED": "Synchronized",
        "LANG_UNSYNCHRONIZED": "Unsynchronized",
        "LANG_RESET_SETTINGS_TO_DEFAULT": "Load Default",
        "LANG_RESTORE_FACTORY_CONFIGURATION": "Restore factory configuration",
        "LANG_RESTORE_DEFAULT": "Restore Default",
        "LANG_DEVICE_MANAGEMENT_HELP_PAGE_0": "Configuration File Management",
        "LANG_CONFIG_DOWNLOAD": "Download",
        "LANG_DOWNLOAD_SUCCESS": "Download success!",
        "LANG_DEVICE_CURRENT_CONFIG_MANAGEMENT": "Current Configuration Management",
        "LANG_CONFIG_CURRENT_AS_DEFAULT": "Save current as default",
        "LANG_DEVICE_UPLOAD_CONFIG_MANAGEMENT": "Upload Configuration Management",
        "LANG_CONFIG_UPLOAD": "Upload",
        "LANG_CONFIG_UPLOAD_AS_DEFAULT": "Upload As Default",
        "LANG_CONFIG_FILE_FINISHED": "The configuration file is imported,please restart the device to take effect!",
        "LANG_UPLOAD_WHEN_END_MAINTAIN": "Upload when End Maintain",
        "LANG_MAINTAIN_PAGE": "Click 'End MainTain', system will automatically upload new data to server.",
        "LANG_END_MAINTAIN": "End Maintain",
        "LANG_MAINTAIN_ERR_1": "Ok: notify ITMS that maintenance is over!",
        "LANG_MAINTAIN_ERR_2": "Error: unable to find TR069 program!",
        "LANG_CANCLE_SETTING_DEFAULT": "Cancel self custom default",
        "LANG_DISABLED": "Disabled",
        "LANG_ENABLED": "Enabled",
        "LANG_VISIBLE": "Visible",
        "LANG_HIDDEN": "Hidden",
        "LANG_WLAN_EASY_MESH_DEVICE_DETAILS": "EasyMesh Device Details Table",
        "LANG_WLAN_EASY_MESH_STA_INFO": "Station Info",
        "LANG_REFRESH": "Refresh",
        "LANG_NODE_INFO": "Node information",
        "LANG_INVALID_MTU_VALUE_YOU_SHOULD_SET_A_VALUE_BETWEEN_650_1500": "Invalid MTU value! You should set a value between 650-1500.",
        "LANG_INVALID_MTU_VALUE_YOU_SHOULD_SET_A_VALUE_BETWEEN_650_1492": "Invalid MTU value! You should set a value between 650-1492.",
        "LANG_INVALID_VLAN_RANGE": "Error. Please enter a positive integer less than 4096, excluding ",
        "LANG_IS_INVALID": "is invalid",
        "LANG_TRY_AGAIN": "please try again",
        "LANG_PPP_USER_NAME_CANNOT_BE_EMPTY": "PPP user name cannot be empty!",
        "LANG_SERVICE_NAME": "Service-Name",
        "LANG_INVALID_SECONDARY_IPV6_DNS_ADDRESS": "Invalid secondary IPv6 DNS address!",
        "LANG_INVALID_PRIMARY_IPV6_DNS_ADDRESS": "Invalid primary IPv6 DNS address!",
        "LANG_INVALID_IPV6_GATEWAY_ADDRESS": "Invalid ipv6 gateway address!",
        "LANG_INVALID_IPV6_PREFIX_LENGTH": "Invalid ipv6 prefix length!",
        "LANG_INVALID_IPV6_ADDRESS": "Invalid ipv6 address!",
        "LANG_SHOULD_NOT_BE_EMPTY": "should not be empty",
        "LANG_CONFIG": "Config",
        "LANG_PORT_BINDING_EXIST": "Only one wan configuration can be bound to a port!",
        "LANG_STRCONNECTEXIST": "Connection already exists!",
        "LANG_BIND_PORT": "Bind Port",
        "LANG_IPV6_PREFIX_LENGTH": "IPv6 Prefix Length",
        "LANG_BRIDGE_IGMP": "Bridge IGMP",
        "LANG_GLOBAL_IP_MODE": "Global Ipv6 mode",
        "LANG_PPP_TYPE": "PPP type",
        "LANG_PLEASE_INPUT_IPV6_ADDRESS_OR_SELECT_DHCPV6_CLIENT_OR_CLICK_SLAAC": "Please input ipv6 address or select DHCPv6 client or click SLAAC!",
        "LANG_PPP_PASSWORD_CANNOT_BE_EMPTY": "PPP password cannot be empty!",
        "LANG_STRMAXVC": "Error: Maximum number of VC exceeds!",
        "LANG_STRTABLEFULL": "Error! Table Full.",
        "LANG_STRMAXNUMPPPOE": "Maximum number of PPPoE connections exceeds in this interface!",
        "LANG_STRADDCHAINERROR": "Error! Add chain record.",
        "LANG_ADDRESS": " Address",
        "LANG_START": "Start",
        "LANG_END": "End",
        "LANG_END_ADDRESS_MUST_BIG_THANSTART_ADDRESS": "End address must equal to or greater than start address",
        "LANG_SERVER": "Server",
        "LANG_INVALID_MAC_ADDR_SHOULD_NOT_EMPTY": "MAC address cannot be empty.",
        "LANG_IP_ADDRESS_CANNOT_BE_EMPTY": "IP address cannot be empty!",
        "LANG_RESERVED_ADDRESS_ALERT": "The reserved address should be in the DHCP address range",
        "LANG_INVALID_LAN_IPV6_IP": "Invalid LAN IPv6 IP!",
        "LANG_INVALID_6RD_PREFIX_ADDRESS": "Invalid 6rd Prefix address!",
        "LANG_INVALID_6RD_PREFIX_LENGTH": "Invalid 6rd Prefix length address!",
        "LANG_START_IP_ADDRESS_CANNOT_BE_EMPTY_FORMAT_IS_IPV6_ADDRESS_FOR_EXAMPLE_2000_0200_10": "Start IP address cannot be empty! Format is IPv6 address (2000:0200:0000:0010)",
        "LANG_INVALID_START_IP": "Invalid Start IP! Format is IPv6 address (2000:0200:0000:0010)",
        "LANG_END_IP_ADDRESS_CANNOT_BE_EMPTY_FORMAT_IS_IPV6_ADDRESS_FOR_EXAMPLE_2000_0200_20": "End IP address cannot be empty! Format is IPv6 address (2000:0200:0000:0020)",
        "LANG_INVALID_END_IP": "Invalid End IP! Format is IPv6 address (2000:0200:0000:0020)",
        "LANG_INVALID_MAXRTRADVINTERVAL_IT_SHOULD_BE_THE_DECIMAL_NUMBER_0_9": "Invalid MaxRtrAdvInterval! It should be the decimal number (0-9)",
        "LANG_MAXRTRADVINTERVAL_MUST_BE_NO_LESS_THAN_4_SECONDS_AND_NO_GREATER_THAN_1800_SECONDS": "MaxRtrAdvInterval must be no less than 4 seconds and no greater than 1800 seconds.",
        "LANG_INVALID_MINRTRADVINTERVAL_IT_SHOULD_BE_THE_DECIMAL_NUMBER_0_9": "Invalid MinRtrAdvInterval! It should be the decimal number (0-9)",
        "LANG_MINRTRADVINTERVAL_MUST_BE_NO_LESS_THAN_3_SECONDS_AND_NO_GREATER_THAN_0_75_MAXRTRADVINTERVAL": "MinRtrAdvInterval must be no less than 3 seconds and no greater than 0.75 * MaxRtrAdvInterval.",
        "LANG_INVALID_LAN_IPV6_PREVIX": "Invalid LAN IPv6 Prefix!",
        "LANG_SSID_CANNOT_BE_EMPTY": "SSID cannot be empty!",
        "LANG_BROADCAST": "Broadcast",
        "LANG_DATA_RATE": "Data Rate",
        "LANG_CONFIGURATION": "Configuration",
        "LANG_FRAGMENT_THRESHOLD": "Fragment Threshold",
        "LANG_BEACON_INTERVAL": "Beacon Interval",
        "LANG_PREAMBLE_TYPE": "Preamble Type",
        "LANG_SHORT_PREAMBLE": "Short Preamble",
        "LANG_LONG_PREAMBLE": "Long Preamble",
        "LANG_INVALID_VALUE_IT_SHOULD_BE_IN_DECIMAL_NUMBER_0_9": "Invalid value. It should be in decimal number (0-9).",
        "LANG_INVALID_VALUE_OF_FRAGMENT_THRESHOLD_INPUT_VALUE_SHOULD_BE_BETWEEN_256_2346_IN_DECIMAL": "Invalid value of Fragment Threshold. Input value should be between 256-2346 in decimal.",
        "LANG_INVALID_VALUE_OF_RTS_THRESHOLD_INPUT_VALUE_SHOULD_BE_BETWEEN_0_2347_IN_DECIMAL": "Invalid value of RTS Threshold. Input value should be between 0-2347 in decimal.",
        "LANG_INVALID_VALUE_OF_BEACON_INTERVAL_INPUT_VALUE_SHOULD_BE_BETWEEN_20_1024_IN_DECIMAL": "Invalid value of Beacon Interval. Input value should be between 20-1024 in decimal.",
        "LANG_RTS_THRESHOLD": "RTS Threshold",
        "LANG_PROTECTION": "Protection",
        "LANG_AGGREGATION": "Aggregation",
        "LANG_SHORT_GI": "Short GI",
        "LANG_DOT11K_SUPPORT": "802.11k Support",
        "LANG_DOT11V_SUPPORT": "802.11v Support",
        "LANG_START_PBC_MSG": "Start PBC successfully!\n\nYou have to run WPS in client within 2 minutes.",
        "LANG_START_PIN_MSG": "Start PIN successfully!\n\nYou have to run WPS in client within 2 minutes.",
        "LANG_INVALID_PIN_LENGTH_THE_DEVICE_PIN_IS_USUALLY_FOUR_OR_EIGHT_DIGITS_LONG": "Invalid PIN length! The device PIN is usually four or eight digits long.",
        "LANG_INVALID_PIN_THE_DEVICE_PIN_MUST_BE_NUMERIC_DIGITS": "Invalid PIN! The device PIN must be numeric digits.",
        "LANG_INVALID_PIN_CHECKSUM_ERRO": "Invalid PIN! Checksum error.",
        "LANG_WLAN_SECURITY_SETTINGS": "WLAN Security",
        "LANG_DEVICE_NAME": "Device Name",
        "LANG_CONTROLLER": "Controller",
        "LANG_WLAN_EASY_MESH_DEVICE_NAME_CANNOT_BE_EMPTY": "Device Name cannot be empty.",
        "LANG_WLAN_EASY_MESH_11KV_ENABLE_WARNING_MESSAGE": "11k or 11v are not enabled in some interfaces, click OK to enable and continue",
        "LANG_WLAN_EASY_MESH_ALERT_VAP1_AUTO_MANAGED_MESSAGE": "Alert: VAP1 for Wlan1 or Wlan2 will be auto-managed. Click OK to continue.",
        "LANG_STA_NUMBER": "Limit Associated Client Number",
        "LANG_CIPHER_SUITE": "Cipher Suite",
        "LANG_ILLEGAL_CHARACTER": "There are illegal characters",
        "LANG_INVALID_LENGTH_OF_KEY_VALUE": "Invalid length of Key value.",
        "LANG_PORT_RANGE_CANNOT_BE_EMPTY_YOU_SHOULD_SET_A_VALUE_BETWEEN_1_65535": "Port range cannot be empty! You should set a value between 1-65535.",
        "LANG_PRE_SHARED_KEY_VALUE_SHOULD_BE_SET_AT_LEAST_8_CHARACTERS": "Pre-Shared Key value should be set at least 8 characters.",
        "LANG_WPA_CIPHER_SUITE_CAN_NOT_BE_EMPTY": "WPA Cipher Suite can not be empty.",
        "LANG_WPA2_CIPHER_SUITE_CAN_NOT_BE_EMPTY": "WPA2 Cipher Suite can not be empty.",
        "LANG_PRE_SHARED_KEY_VALUE_SHOULD_BE_64_CHARACTERS": "Pre-Shared Key value should be 64 characters.",
        "LANG_USERNAME_TITLE": "Username",
        "LANG_OLD_PASSWORD_TITLE": "Old Password",
        "LANG_NEW_PASSWORD_TITLE": "New Password",
        "LANG_AFFIRM_PASSWORD_TITLE": "Confirm Password",
        "LANG_PSWD_SHOULD_NOT_BE_SAME": "The new password and old password should not be same!",
        "LANG_PSWD_IS_INVALID": "This new password cannot be used ,please check and try again!",
        "LANG_ERROR_INPUT_OLD_USER_PASSWORD_ERROR": "ERROR: Input Old user password error!",
        "LANG_SUBMIT_SUCCESS": "Submit Success",
        "LANG_PASSWORD_CANNOT_BE_EMPTY_PLEASE_TRY_IT_AGAIN": "Password cannot be empty. Please try it again.",
        "LANG_NEW_PASSWORD_CAN_NOT_BE_EMPTY_INPUT_AGAIN": "New password is a required field!",
        "LANG_NEW_PASSWORD_ERROR_INPUT_PASSWORD_AGAIN": "New Password Error, Input Password Again!",
        "LANG_MGM_USER_PASSWORD_RULE1": "The password must contain at least 6 characters.",
        "LANG_MGM_USER_PASSWORD_RULE2": "The password must Input Max 16 charactors.",
        "LANG_MGM_USER_PASSWORD_RULE3": "The password must contain at least two of the following combinations:",
        "LANG_MGM_USER_PASSWORD_RULE4": "0-9, a-z, A-Z, Special characters (. _ / @ ! ~ # $ % ^ * ( ) + : ?).",
        "LANG_AFFIRM_PASSWORD_CAN_NOT_BE_EMPTY_INPUT_AGAIN": "Confirm Password is a required field!",
        "LANG_AFFIRM_PASSWORD_DO_NOT_MATCH_NEW_PASSWORD_INPUT_AGAIN": "Confirm Password Don't Match New Password, Input Password Again!",
        "LANG_BIND_MODE": "Bind Mode",
        "LANG_PORT": "Port",
        "LANG_INVALID_VLAN_ID": "Invalid VLAN ID!",
        "LANG_INVALID_VLAN_RANGE2": "Please enter a positive integer less than 4096",
        "LANG_VLAN_ID_IS_RESERVED": "VLAN ID is reserved!",
        "LANG_NET_VLAN_MAPPING_ERR_3": "VLAN ID pairs are not allowed to repeat,please try again.",
        "LANG_NET_VLAN_MAPPING_ERR_1": "VLAN ID must be completed in pairs, please try again.",
        "LANG_BIND_CONFIG": "Bind Settings",
        "LANG_TR069_CLIENT_CONFIGURATION": "TR069 Client Configuration",
        "LANG_SERVER_URL": "Server URL",
        "LANG_ENABLE_CERTIFICATE": "Enable Certificate",
        "LANG_PERIODIC_REPORT": "Periodic Report",
        "LANG_PERIODIC_REPORT_INTERVAL": "Periodic Report Interval",
        "LANG_CONNECT_REQUEST_USERNAME": "Connect Request Username",
        "LANG_CONNECT_REQUEST_PASSWORD": "Connect Request Password",
        "LANG_LLID_CONFIG": "LOID Config",
        "LANG_PLOAM_CONFIG": "PonPwd Config",
        "LANG_TRUSTED_CA_CERTIFICATE": "Trusted authority certification (CA) Certificate",
        "LANG_CERTIFICATE_IMPORT": "Certificate Import",
        "LANG_DELETE_CERT": "Delete the Uploaded Certificate",
        "LANG_UPLOAD_SUCCESS": "Upload Success!",
        "LANG_DELETE_SUCCESS": "Delete Success!",
        "LANG_NET_TR069_ERROR_1": "ACS URL is an illegal URL!",
        "LANG_NET_TR069_ERROR_2": "The periodic report interval must be a positive integer! ",
        "LANG_NET_TR069_ERROR_3": "ACS username contains illegal characters, please input it again!",
        "LANG_NET_TR069_ERROR_4": "ACS password contains illegal characters, please input it again!",
        "LANG_NET_TR069_ERROR_5": "The connect requst username contains illegal characters, please input it again!",
        "LANG_NET_TR069_ERROR_6": "The connect requst password contains illegal characters, please input it again!",
        "LANG_LLID_CONFIG_ERR_1": "contains invalid characters or the length of it is not between 1-24 bytes, please re-enter! ",
        "LANG_TIMER_CONFIG": "Time",
        "LANG_TIME_ZONE_SELECT": "Time Zone Select",
        "LANG_ENABLE_DAYLIGHT_SAVING_TIME": "Enable Daylight Saving Time",
        "LANG_ENABLE_SNTP_CLIENT_UPDATE": "Enable SNTP Client Update",
        "LANG_PRIMARY": "Primary",
        "LANG_STANDBY": "Standby",
        "LANG_SYNCHRONIZING_TYPE": "Sync Channel",
        "LANG_SYNCHRONIZING_WAN_INTERFAVE": "Sync with WAN",
        "LANG_INTERVAL": "Interval",
        "LANG_NTP_SERVER_OTHER1": "primary ntp server is other, but other is null",
        "LANG_NTP_SERVER_OTHER2": "secondary ntp server is other, but other is null",
        "LANG_INTERVAL_SHOULD_NOT_BE_0": "Sync interval should not be 0",
        "LANG_RIP": "RIP",
        "LANG_INPUT_CONFIGURATION": "Please input configuration",
        "LANG_RECEIVE_MODE": "Receive Mode",
        "LANG_SEND_MODE": "Send Mode",
        "LANG_DELETE_SELECTED": "Delete Selected",
        "LANG_DELETE_ALL": "Delete All",
        "LANG_ENTRY_ALREADY_EXISTS": "Entry already exists!",
        "LANG_THERE_IS_NO_ITEM_SELECTED_TO_DELETE": "There is no item selected to delete!",
        "LANG_STATIC_ROUTER": "Static Route",
        "LANG_DESTINATION": "Destination",
        "LANG_GATEWAY": "Gateway",
        "LANG_METRIC": "Metric",
        "LANG_SHOW_ROUTES": "Show Routes",
        "LANG_IP_ROUTE_TABLE": "IP Route Table",
        "LANG_THE_SPECIFIED_MASK_PARAMETER_IS_INVALID_DESTINATION_MASK_DESTINATION": "The specified mask parameter is invalid. (Destination & Mask) != Destination.",
        "LANG_CHECK_IP_ERR_1": "IP address cannot be empty! It should be filled with 4 digit numbers as xxx.xxx.xxx.xxx.",
        "LANG_CHECK_IP_ERR_2": "Invalid IP address value. It should be the decimal number (0-9).",
        "LANG_CHECK_IP_ERR_3": "Invalid IP address value.",
        "LANG_CHECK_IP_ERR_4": "Invalid IP address range in 1st digit. It should be 1-223.",
        "LANG_CHECK_IP_ERR_5": "Invalid IP address range in 2nd digit. It should be 0-255.",
        "LANG_CHECK_IP_ERR_6": "Invalid IP address range in 3rd digit. It should be 0-255.",
        "LANG_CHECK_IP_ERR_7": "Invalid IP address range in 4th digit. It should be 0-255.",
        "LANG_INVALID_IPV4_SUBNET_SHOULD_NOT_EMPTY": "Subnet mask cannot be empty! It should be filled with 4 digit numbers as xxx.xxx.xxx.xxx.",
        "LANG_INVALID_IPV4_SUBNET_SHOULD_BE_DECIMAL_NUM": "Invalid subnet mask value. It should be the decimal number (0-9).",
        "LANG_INVALID_IPV4_SUBNET_DIGIT": "Invalid subnet mask digit. It should be the number of 0, 128, 192, 224, 240, 248, 252 or 254.",
        "LANG_ENTER_NEXT_HOP_IP_OR_SELECT_A_GW_INTERFACE": "Enter Next Hop IP or select a GW interface!",
        "LANG_INVALID_METRIC_RANGE_IT_SHOULD_BE_0_16": "Invalid Metric range. It should be 0~16.",
        "LANG_VOIP_HELP_PAGE_2": "VOIP Basic",
        "LANG_SERVER_TYPE": "Server Type",
        "LANG_PRIMARY_SIP_REG": "Primary SIP Register",
        "LANG_REGISTER": "Register",
        "LANG_PROXY": "Proxy",
        "LANG_SUBSCRIBE": " Subscribe",
        "LANG_OUTBOUND": "Outbound",
        "LANG_START_PORT": "Start Port",
        "LANG_EXPIRE": " Expire (sec)",
        "LANG_LOCAL": "Local",
        "LANG_USER_NUMBER": "User Number",
        "LANG_USER_LOGIN": "User Account",
        "LANG_USER_PASSWORD": "User Password",
        "LANG_PACKET_TIME": "Packet Time",
        "LANG_VOIP_ADVANCE_CONFIG": "VOIP Advance Settings",
        "LANG_VOIP_BASIC_CONFIG": "VOIP Basic Settings",
        "LANG_LEC": "Echo Suppression Settings",
        "LANG_SYNC_PHONE_TIME": "Sync Phone time",
        "LANG_CALLER_ID_MODE": "Caller ID Mode",
        "LANG_REGION": "Region",
        "LANG_VOIP_HB_PASSIVE_OPTION": "Passive Option",
        "LANG_VOIP_HB_ACTIVE_REGISTER": "Active Register",
        "LANG_VOIP_HB_ACTIVE_OPTION": "Active Option",
        "LANG_HEART_BEAT_CYCLE": "Heart beat cycle",
        "LANG_NO_ANSWER_TIMER": "No Answer Timer",
        "LANG_SEND_GAIN": "Send gain",
        "LANG_RECV_GAIN": "Recv gain",
        "LANG_USER_ACCOUNT": "User Account",
        "LANG_FLASH_TIME": "Flash Time",
        "LANG_DAIL_PLAN_ENABLE": "Dial plan enable",
        "LANG_MAX_MATCH": "Max match",
        "LANG_DAIL_PLAN": "Dial Plan",
        "LANG_CODEC": "Codec",
        "LANG_LINE": "Line",
        "LANG_PRIORITY": "Priority",
        "LANG_SESSION_EXPIRE_SEC": "Session Expire (sec)",
        "LANG_FLASH_HOOK_TIME": "Flash hook time (ms), [times of 10, min: 80, max: 2000]",
        "LANG_OFF_HOOK_ALARM": "Dial Tone Duration (sec)",
        "LANG_SHORT_DIGIT_TIMER": "Short digit timer (sec)",
        "LANG_LONG_DIGIT_TIMER": "Long digit timer (sec)",
        "LANG_BUSY_TONE_TIME": "Busy tone Duration (sec)",
        "LANG_HOWLER_TIME": "Howler tone Duration (sec)",
        "LANG_REG_RETRY_INTERVAL": "Register retry interval",
        "LANG_HEART_BEAT_MODE": "Heart beat Mode",
        "LANG_POLAR_REVERSAL": "Polarity Reversal",
        "LANG_CALL_WAIT": "Call Waiting",
        "LANG_3PTY_CONFERENCE": "3PTY Conference",
        "LANG_HOT_LINE_ENABLE": "HotLine Enable",
        "LANG_HOT_LINE_TIMEOUT": "HotLine Timerout",
        "LANG_HOT_LINE_NUMBER": "Hot Line Number",
        "LANG_UNCOND_FORWARD": "Uncondition Forward",
        "LANG_UNCOND_NUM": "Uncondition Forward Num",
        "LANG_BUSY_FORWARD": "Busy Forward",
        "LANG_BUSY_FORWARD_NUM": "Busy Forward Num",
        "LANG_NO_ANSWER_FORWARD": "No Answer Forward",
        "LANG_NO_ANSWER_FORWARD_NUM": "No Answer Forward Num",
        "LANG_NO_ANSWER_FORWARD_TIME": "No Answer Forward Time",
        "LANG_CALL_TRANSFER": "Call Transfer",
        "LANG_UNATTEND_TRANSFER": "Unattend Transfer (E, F, 0~9)",
        "LANG_ATTEND_TRANSFER": "Attend Transfer (E, F, 0~9)",
        "LANG_INVALID": "is invalid",
        "LANG_NEED_ACCOUNT": "need account",
        "LANG_APP_VOIP_ERR": "Line 1 has the same number as line 2",
        "LANG_APP_VOIP2_ERR": "Broadband telephone advanced setting error, same setting in different priority sequence!",
        "LANG_DOMAIN": "Domain",
        "LANG_ALG": "ALG",
        "LANG_DMZ_HOST_TITLE": "DMZ Host",
        "LANG_DMZ_IP_ADDRESS_TITLE": "DMZ Host IP Address",
        "LANG_NAT_DMZ_HOST": "DMZ Hosts",
        "LANG_NAT_VIRTUAL_SERVER_CONFIGURATION": "Virtual Server Configuration",
        "LANG_EXTERNAL_IP_ADDRESS": "External IP Address",
        "LANG_EXTERNAL_START_PORT": "External Start Port",
        "LANG_EXTERNAL_END_PORT": "External End Port",
        "LANG_SERVER_IP_ADDR": "Server IP Address",
        "LANG_SOURCE_PORT": "Source Port",
        "LANG_SERVER_NAME": "Server Name",
        "LANG_DYNAMIC_DNS_2": "Dynamic DNS",
        "LANG_ENABLE_DDNS_SERVICE": "Enable DDNS Service",
        "LANG_HOSTNAME": "Hostname",
        "LANG_SERVICE": "Service",
        "LANG_ADD_DYNAMIC_DNS": "Add dynamic DNS",
        "LANG_ORAY_COM": "oray.com",
        "LANG_DDNS_PROVIDER": "DDNS Provider",
        "LANG_EMAIL": "Email",
        "LANG_KEY": "Key",
        "LANG_ADD_DDNS_ERR_1": "Please enter a valid hostname",
        "LANG_ADD_DDNS_ERR_2": "Please enter a valid username",
        "LANG_ADD_DDNS_ERR_3": "Please enter a valid password",
        "LANG_INVALID_EMAIL": "Invalid email.",
        "LANG_INVALID_KEY": "Invalid key.",
        "LANG_UPNP_CONFIG": "UPnP Configuration",
        "LANG_RSTBTN_CONFIG": "ReSet Configuration",
        "LANG_RSTBTN_SWITCH": "Block Reset Button",
        "LANG_IGMP_SNOOPING_CONFIG": "IGMP Snooping Configuration",
        "LANG_IGMP_PROXY": "IGMP Proxy",
        "LANG_INTERNET_CONNECTION": "Internet Connection",
        "LANG_MLD_SNOOPING_CONFIG": "MLD Snooping",
        "LANG_MLD_PROXY": "MLD Proxy",
        "LANG_MCAST_VLAN": "Multicast Vlan",
        "LANG_MULTICAST_VLAN_TITLE": "Multicast VLAN (blank indicates no setting)",
        "LANG_SYSTEM_LOG": "System Log",
        "LANG_RECORD_TITLE": "Log",
        "LANG_RECORD_LEVEL_TITLE": "Log Level",
        "LANG_DISPLAY_LEVEL_TITLE": "Display Level",
        "LANG_NAT_CONFIG_HELP_PAGE_VIRTUAL_6": "Server IP Address",
        "LANG_SERVER_UDP_PORT_TITLE": "Server UDP Port",
        "LANG_DEVICE_LOG": "LOG Info",
        "LANG_DOWNLOAD_LOG": "Download Log",
        "LANG_CLEAR_RECORDS": "Clear Records",
        "LANG_SYSTEM_ACCESS_LOG": "System Access Log",
        "LANG_DATE_TIME": "Date/Time",
        "LANG_SEVERITY": "Severity",
        "LANG_INFO": "Info",
        "LANG_ACCESS_RECORDS": "Access Records",
        "LANG_SYS_LOG_ALERT0": "There is not any system log.",
        "LANG_SERVER_UDP_PORT": "Server UDP Port",
        "LANG_SYSLOG_CONFIGURATION_PAGE_1": "If enabled syslog mode,system start to log events which loglevel is equal or higher than your settings.",
        "LANG_SYSLOG_CONFIGURATION_PAGE_2": "For the display level, all events that are equal to or higher than the selected level will be displayed.",
        "LANG_SYSLOG_CONFIGURATION_PAGE_3": "If select mode 'Remote' or 'Both' log events will be sent to both remote syslog server IP and Port",
        "LANG_SYSLOG_CONFIGURATION_PAGE_4": "If select mode 'Local' or 'Both' log events will be logged to local.",
        "LANG_SYSLOG_CONFIGURATION_PAGE_5": "Select,then click 'Save/Apply' to configuration",
        "LANG_DESTINATION_ADDRESS": "Dest IP Address",
        "LANG_WAN_INTERFACE": "WAN Interface",
        "LANG_PING_TEST": "PING Test",
        "LANG_TRACERT_TEST": "Tracert Test",
        "LANG_PING_ERR_1": "Incorrect destination address or WAN interface!",
        "LANG_PING_ERR_2": "No corresponding WAN interface has been found!",
        "LANG_PLEASE_WAIT": "Please wait...",
        "LANG_PING_TEST_FAILED": "Ping test failed!",
        "LANG_RESULT": "Result",
        "LANG_TRACERT_ERR_1": "Invalid address!",
        "LANG_TRACERT_ERR_2": "Tracert test failed.",
        "LANG_TR069_INFORM": "TR069 Inform",
        "LANG_LOOPBACK_TEST": "Loopback Test",
        "LANG_ENABLE_LOOPBACK_DETECTION": "Enable Loopback Detection",
        "LANG_DETECTION_FRAME_INTERVAL": "Detection Frame Interval",
        "LANG_RECOVER_FRAME_INTERVAL": "Recover Frame Interval",
        "LANG_ETHERTYPE": "EtherType",
        "LANG_PORT_LOOPBACK_DETECT_STATE": "Port Loopback Detect State",
        "LANG_NO_LOOPBACK": "No Loopback",
        "LANG_LOOPBACK_DETECTE_RESULT_1": "Loopback Detected and Port Closed",
        "LANG_LOOPBACK_DETECTE_RESULT_2": "Loopback Detected but Port not Closed",
        "LANG_LOOPBACK_DETECTE_ERR_1": "Loopback frame interval 1~60S",
        "LANG_LOOPBACK_DETECTE_ERR_2": "Recover frame interval 60~1800",
        "LANG_LOOPBACK_DETECTE_ERR_3": "EtherType should be hexadecimal",
        "LANG_LOOPBACK_DETECTE_ERR_4": "must specify VLAN ID",
        "LANG_LOOPBACK_TEST_PAGE": "Use ',' to separate means untagged (eg. 0, 45, 46)",
        "LANG_URL_FILTER_ENABLE": "Enable URL Filtering",
        "LANG_URL_FILTER": "URL Filtering",
        "LANG_FILTER_MODE": "Filtering Mode",
        "LANG_BLACK_LIST": "BlackList",
        "LANG_WHITE_LIST": "WhiteList",
        "LANG_FILTER_RULE_LIST": "Filter Rule List",
        "LANG_LIST_LIMIT": "Add 100 rules at most",
        "LANG_INVALID_URL_ADDR_SHOULD_NOT_EMPTY": "Url addresss should not empty",
        "LANG_URL_ADDRESS": "Url address",
        "LANG_RULE_ALREADY_EXISTS": "Rule already exists",
        "LANG_MAX_RULES": "Max number of rules reached",
        "LANG_ADD_REEOR": "failed to add",
        "LANG_DELETE_ERROR": "failed to delete",
        "LANG_SELECT_FIREWALL_LEVEL": "Select Firewall Level",
        "LANG_LOW": "Low",
        "LANG_HIGH": "High",
        "LANG_SECURITY_CLASSIFY": "Security Classify Configuration",
        "LANG_ATTACK_PROTECTION_CONFIG": "Attack Protection",
        "LANG_WHITE_LIST_COMMENT": "MAC address filtering in bridge mode is not supported. Please add a MAC before applying the whitelist.",
        "LANG_MAC_FILTER_ENABLE": "Enable MAC Address Filtering",
        "LANG_WHITELIST_CTRL": "The whitelist has been cleared, please switch to blacklist or turn off MAC filtering",
        "LANG_COMMON_PORT_FILTERING": "Common Filtering",
        "LANG_FILTERING": "Filtering",
        "LANG_IP_FILTER_FUNCTION_DESCRIPTION": "Click submit to enable/disable IP/Port filtering function. When white list is not empty, white list works instead of black list.",
        "LANG_UPSTREAM": "Upstream",
        "LANG_BLACK_LIST_NOTE": "When black list enabled, default allow all LAN upstreams, add black list filter rules to prevent specified LAN upstreams",
        "LANG_WHITE_LIST_NOTE": "When white list enabled, default deny all WAN downstreams, add white list filter rules to allow specified WAN downstreams",
        "LANG_RSTBTN_NOTE": "When this button is turned on, the hardware reset button cannot be used", 
        "LANG_NAME": "Name",
        "LANG_SOURCE": "Source",
        "LANG_DESTINATION_PORT": "Destination Port",
        "LANG_ADD_IP_FILTER_OUT": "Add IP/Port Filter - Out",
        "LANG_ADD_IP_FILTER_INCOMING": "Add IP/Port Filter - Incoming",
        "LANG_FILTER_NAME": "Filter Name",
        "LANG_PREFIX_LENGTH": "Prefix Length",
        "LANG_START_ADDRESS": "Start Address",
        "LANG_END_ADDRESS": "End Address",
        "LANG_MAX_VIRTUAL_SERVER_RULES": "Sorry, max server rules limited",
        "LANG_SETTING_ERROR": "Wrong setting is found!",
        "LANG_FILTER_ADD_ERROR_2": "The source IP end address must be matched with the source IP start address",
        "LANG_FILTER_ADD_ERROR_3": "The destination IP end address must be matched with the destination IP start address",
        "LANG_FILTER_ADD_ERROR_4": "Source subnet mask must match the source IP address",
        "LANG_FILTER_ADD_ERROR_5": "The destination subnet mask must be matched with the destination IP address",
        "LANG_FILTER_ADD_ERROR_8": "The source IP start address cannot be greater than the end address",
        "LANG_FILTER_ADD_ERROR_9": "Cannot insert the source subnet mask when setting the source IP range",
        "LANG_FILTER_ADD_ERROR_11": "The destination IP start address cannot be greater than the end address",
        "LANG_FILTER_ADD_ERROR_12": "The destination subnet mask cannot be entered when setting the range of the destination IP",
        "LANG_INVALID_SOURCE_IPV6_PREFIX_LENGTH": "Invalid Source IPv6 prefix length!",
        "LANG_INVALID_SOURCE_IPV6_END_ADDRESS": "Invalid Source IPv6 End address!",
        "LANG_INVALID_DESTINATION_IPV6_START_ADDRESS": "Invalid Destination IPv6 Start address!",
        "LANG_INVALID_DESTINATION_IPV6_PREFIX_LENGTH": "Invalid destination IPv6 prefix length!",
        "LANG_INVALID_DESTINATION_IPV6_END_ADDRESS": "Invalid Destination IPv6 End address!",
        "LANG_FILTER_ADD_ERROR_1": "The port number must be selected with TCP or UDP",
        "LANG_FILTER_ADD_ERROR_6": "The end source port must be matched with the starting source port",
        "LANG_FILTER_ADD_ERROR_7": "The end  destination port must be matched with the starting destination port",
        "LANG_SOURCE_START_PORT": "The source start port",
        "LANG_SOURCE_END_PORT": "The source end port",
        "LANG_FILTER_ADD_ERROR_10": "The source start port cannot be greater than the end port",
        "LANG_DESTINATION_START_PORT": "The destination start port",
        "LANG_DESTINATION_END_PORT": "The destination end port",
        "LANG_FILTER_ADD_ERROR_13": "The destination start port cannot be greater than the end port",
        "LANG_FILTER_ADD_ERROR_14": "Please set filtering rules",
        "LANG_REMOTE_HOST": "Remote Host",
        "LANG_PLEASE_SELECT_AN_ENTRY_TO_DELETE": "Please select an entry to delete!",
        "LANG_URL_FILTER_NOTE": "Do not add HTTP and WWW before URL, eg. if you need to block http://www.example.com, just input example.com",
        "LANG_THE_MAXIMUM_NUMBER_OF_ENTRIES_ARE_16": "The maximum number of entries are 16.",
        "LANG_ENTRY_EXIST": "Entry already exists",
        "LANG_FILTERLEVEL_IS_HIGH": "When firewall level is high,port filtering is not configurable",
        "LANG_LOGIN_PRIVILEGE": "Login Privilege",
        "LANG_MASK": "Mask",
        "LANG_IP_QOS": "IP QoS",
        "LANG_TOTAL_BANDWIDTH_LIMIT": "Total Bandwidth Limit",
        "LANG_REMARK_ENABLE": "Remark Enable",
        "LANG_REMARK_MODE": "Remark Mode",
        "LANG_TRANSPARENT_MODE": "Transparent Mode",
        "LANG_OVER_WRITE": "Over Write",
        "LANG_POLICY": "Policy",
        "LANG_PRIO": "PRIO",
        "LANG_QUEUE": "Queue",
        "LANG_WRR": "WRR",
        "LANG_QOS_CONFIG": "Qos Config",
        "LANG_QOS_CLASSIFICATION": "QoS Classification",
        "LANG_TOTAL_WRR_LIMIT": "The total combination of WRR policy weights must be 100",
        "LANG_MARK": "Mark",
        "LANG_CONNECT_TYPE": "Connect Type",
        "LANG_VERSION": "Version",
        "LANG_ADD_IP_QOS_TRAFFIC": "Add IP QoS Traffic Shaping Rule",
        "LANG_FLOW_CONTROL_TYPE_NAME": "Flow control type name",
        "LANG_IP_PROTOCOL_VERSION": "IP protocol version",
        "LANG_FILTER_ADD_ERROR_15": "Please specify IP protocol version",
        "LANG_NET_QOS_CLS_PAGE_5": "Specify IP Priority Tags",
        "LANG_NET_QOS_CLS_PAGE_6": "Specify DSCP Tag",
        "LANG_NET_QOS_CLS_PAGE_7": "If the WAN port 802.1p is enabled, set the 802.1p value",
        "LANG_MODE_SELECTION": "ModE Selection",
        "LANG_GENERAL_MODE": "General mode",
        "LANG_APPLICATION_TYPE": "Application type",
        "LANG_PHYSICAL_LAN_PORT": "Physical LAN Port",
        "LANG_DSCP_CHECK": "DSCP Check",
        "LANG_8021P_PROORITY": "802.1p Priority",
        "LANG_SOURCE_IP_ADDRESS": "Source IP Address",
        "LANG_SOURCE_SUBNET_MASK": "The source subnet mask",
        "LANG_DESTINATION_IP_ADDRESS_TITLE": "Destination IP Address",
        "LANG_DESTINATION_SUBNET_MASK": "The destination subnet mask",
        "LANG_SOURCE_PREFIX_LENGTH_TITILE": "Source Prefix Length",
        "LANG_DESTINATION_PREFIX_LENGTH_TITILE": "Destination Prefix Length",
        "LANG_SOURCE_PORT_TITLE": "Source Port (port or port:port)",
        "LANG_DESTINATION_PORT_TITLE": "Destination Port (port or port:port)",
        "LANG_SOURCE_MAC_TITLE": "Source MAC (xx:xx:xx:xx:xx:xx)",
        "LANG_DESTINATION_MAC_TITLE": "Destination MAC (xx:xx:xx:xx:xx:xx)",
        "LANG_PAGE_DESC_CLASSICY_QOS_RULE_EXTRA": "After add a new rule, please click 'Apply Changes' to take effect.",
        "LANG_NET_QOS_CLS_ERROR_1": "Flow control type name contains illegal characters, please try again!",
        "LANG_NET_QOS_CLS_ERROR_2": "Please select the IP priority mark!",
        "LANG_NET_QOS_CLS_ERROR_3": "At least one traffic control condition must be configured!",
        "LANG_NET_QOS_CLS_ERROR_4": "Illegal input of source IP address",
        "LANG_NET_QOS_CLS_ERROR_5": "The source subnet mask format is illegal !",
        "LANG_NET_QOS_CLS_ERROR_6": "The destination IP address is illegal",
        "LANG_INVALID_SOURCE_IPV6_ADDRESS": "Invalid Source IPv6 address!",
        "LANG_NET_QOS_CLS_ERROR_7": "Invalid IPv6 prefix length",
        "LANG_NET_QOS_CLS_ERROR_8": "Invalid IPv6 IP destination address",
        "LANG_NET_QOS_CLS_ERROR_9": "Incorrect prefix length for IPv6 destination address",
        "LANG_NET_QOS_CLS_ERROR_10": "Illegal destination subnet mask",
        "LANG_NET_QOS_CLS_ERROR_11": "Illegal source start port",
        "LANG_NET_QOS_CLS_ERROR_12": "The protocol is not TCP/UDP,the port cannot be specified",
        "LANG_NET_QOS_CLS_ERROR_13": "Illeagal source end port ",
        "LANG_NET_QOS_CLS_ERROR_14": "Illeagal destination start port ",
        "LANG_NET_QOS_CLS_ERROR_15": "Illeagal destination end port ",
        "LANG_NET_QOS_CLS_ERROR_16": "Invalid source MAC address",
        "LANG_NET_QOS_CLS_ERROR_17": "Invalid destination MAC address",
        "LANG_INVALID_DESTINATION_VALUE": "Invalid Destination value.",
        "LANG_TRAFFIC_CONTROL": "Traffic Control",
        "LANG_RATE": "Rate",
        "LANG_DIRECTION": "Direction",
        "LANG_RATE_LIMIT": "Rate Limit",
        "LANG_DOWNSTREAM": "Downstream",
        "LANG_WAN_INTERFACE_NOT_ASSIGNED": "wan interface not assigned!",
        "LANG_SOURCE_IP_INVALID": "Source IP invalid!",
        "LANG_DESTINATION_IP_INVALID": "Destination IP invalid",
        "LANG_SOURCE_IP_MASK_INVALID": "Source IP Mask invalid",
        "LANG_DESTINATION_IP_MASK_INVALID": "Destination IP Mask invalid",
        "LANG_SOURCE_PORT_INVALID": "Source Port invalid",
        "LANG_PLEASE_ASSIGN_TCP_UDP": "Please assign TCP/UDP!",
        "LANG_DESTINATION_PORT_INVALID": "Destination Port invalid",
        "LANG_UPLINK_RATE_INVALID": "uplink rate invalid",
        "LANG_INVALID_DESTINATION_IPV6_ADDRESS": "Invalid Destination IPv6 address!",
        "LANG_THE_RATE_MUST_MULTIPLE_OF_FOT": "The rate must be a multiple of 512",
        "LANG_SOURCE_MASK": "Source Mask",
        "LANG_DESTINATION_MASK": "Destination Mask",
        "LANG_SOURCE_PREFIX_LENGTH": "Source Prefix Length",
        "LANG_DESTINATION_PREFIX_LENGTH": "Destination Prefix Length",
        "LANG_MGM_USER_PASSWORD_RULE0": "It is recommended to change your default password for this device for security and safety reasons.",
        "LANG_WARNING_WRONG_PASSWORD": "ERROR: wrong password!",
        "LANG_NEXT_STEP": "Next Step",
        "LANG_BACK": "Back",
        "LANG_QUICK_GUIDE": "Quick Guide",
        "LANG_QUICK_GUIDE_TIPS1": "If you don't know the PPPoE account and password, please contact your local Internet service provider.",
        "LANG_QUICK_GUIDE_TIPS2": "If you are accessing the page via Wi-Fi, please refresh the page manually after submit.",
        "IPv6 WAN Info": "IPv6 WAN Info",
        "IPv6 Network Info": "IPv6 Network Info",
        "LANG_PARAMETER": "Paramete",
        "LANG_CONNECTED": "Connected",
        "LANG_NOT_CONNECTED": "Not Connected",
        "LANG_NOT_SUPPORT": "not support",
        "LANG_USB_PARTITION_SELECTION": "USB Partition Selection",
        "LANG_CONFIG_RECOVERY": "Configure Quick Recovery",
        "LANG_SAVE_FAILED": "Save failed.",
        "LANG_BACKUP_CONFIGRUTION": "Backup Configuration",
        "LANG_USB_UNLOAD": "USB Unload",
        "LANG_BACKUP_IS_EXIST": "Configuration backup file already exists!",
        "LANG_BACKUP_AFTER_DELETE": "Backup after deletion",
        "LANG_NOT_ENOUGH_SPACE": "Not enough space",
        "LANG_SAVE_SUCCESSFULLY": "Saved successfully",
        "LANG_UNLOAD_SUCCESSFULLY": "Unload successfully",
        "LANG_UNLOAD_FAILED": "Unload failed",
        "LANG_USB_FILE_DIRECTORY": "USB remote download file storage directory",
        "LANG_REMOTE_URL": "Remote URL",
        "LANG_STORAGE_NOTE_1": "Note: URL format:(Protocol)://(Host)/(File path)/(File name), Protocol support http and ftp",
        "LANG_DOWNLOAD": "Download",
        "LANG_APP_STORAGE_ERR_3": "Please enter a valid port number!",
        "LANG_APP_STORAGE_ERR_4": "Please enter a valid remote FTP URL!",
        "LANG_USBP_DEVICE_MAKE": "Device Maker",
        "LANG_USBP_MGM": "USB Printer",
        "LANG_STORAGE": "Home Storage",
        "LANG_DOWNLOAD_FAIL": "Download fail!",
        "LANG_EDIT": "Edit",
        "LANG_OTHER_MANAGEMENT": "Other Manage",
        "LANG_WAN_MODE": "Uplink Mode",
        "LANG_WAN_MODE_AUTO": "PON Auto Switch",
        "LANG_WAN_MODE_NOTE": "Device will auto reboot after switching uplink mode!",
        "LANG_PPPOE_INFO": "PPPOE Info",
        "LANG_PPPOE_ACNAME": "AC Name",
        "LANG_UPNP_ERR_1": "Error: The WAN interface cannot be empty",
		    "LANG_TO":" Total ",
		    "LANG_PER_PAGE":" Rows Per Page",
        "LANG_PLDT_PASSWORD_RULE0": "The password must contain at least 8 characters.",
        "LANG_PLDT_PASSWORD_RULE1": "The password must Input Max 15 charactors.",
        "LANG_PLDT_PASSWORD_RULE2": "The password must contain at least three of the following combinations:",
        "LANG_STUN_CONFIG": "STUN Config",
        "LANG_STUN": "STUN",
        "LANG_SERVER_PORT": "Server Port",
        "LANG_SIGNAL_STRENGTH": "Signal (dBm)",
        "LANG_DETECT": "Detect",
        "LANG_AP_DETECT_ERROR": "Please turn on WLAN to do AP detect!",
        "LANG_AP_DETECT": "AP Detect",
        "LANG_IPERF_TEST": "Iperf Test",
        "LANG_USB_BACKUP_CONFIG_RESTORE_AND_REBOOT": "USB Backup Config Restore And Reboot",
        "LANG_USB_BACKUP_CONFIG_RESTORE_SUCCESS": "USB Backup Config Restore Success",
        "LANG_USB_BACKUP_CONFIG_RESTORE_ERR1": "Restore Error:Please enable the configuration quick recovery function!",
        "LANG_USB_BACKUP_CONFIG_RESTORE_ERR2": "Restore Error:If the backup configuration file is not found, back up the configuration first.",
        "LANG_USB_BACKUP_CONFIG_RESTORE_ERR3": "Restore Error.",
    }
}

$(document).ready(function () {
    $(".lang").each(function (index, element) {
        $(this).text(arrLang["en"][$(this).attr("key")]);
    });
    $("#ajax_load_file").prop("src", "js/" + $(".title_flag").attr("flag") + "_control.js");
});
