var arrLang = {
    "zh": {
        "LANG_HORIZONTAL" : "水平的",
        "LANG_VERTICAL" : "垂直的",
        "LANG_MENU_LAYOUT_SELECT" : "菜单布局选择",
        "LANG_FAMILY_GROUP_MANAGEMENT" : "家庭组管理",
        "IPERF_TEST_INSTRUCTION1" : "配合软件 'Magic iPerf' 进行wlan基本测速",
        "IPERF_TEST_INSTRUCTION2" : "选择一个在线设备, 点击开始",
        "IPERF_TEST_INSTRUCTION3" : "1. 'Magic iPerf' 执行 'iperf3 -c [网关ip] -i 1' 测试上行速率",
        "IPERF_TEST_INSTRUCTION4" : "2. 'Magic iPerf' 执行 'iperf3 -s -i 1' 测试下行速率",
        "LANG_STATIC_ROUTE_TIPS2" : "请选择一条可用的 WAN 接口",
        "LANG_STATIC_ROUTE_TIPS" : "设置静态路由需要至少一条可用的 WAN",
        "LANG_DMZ_TIPS" : "DMZ IP应与局域网IP位于同一网段(且不同于局域网IP)",
        "LANG_MAC_FILTER_ADD_TIPS": "列表修改后，需要再次应用 MAC 地址过滤才能生效。",
        "LANG_SUBMIT_FAIL" : "应用失败",
        "LANG_MAC_FILTER": "MAC 过滤",
        "LANG_UPDATE": "自动刷新",
        "LANG_WRIELESS_PERFORMANCE": "无线性能状态",
        "LANG_CAP_TYPE": "抓包类型",
        "LANG_MANAGE_FRAME": "管理帧",
        "LANG_WLAN_FRAME_CAP": "无线帧抓取",
        "LANG_PON_AUTH_LOG": "PON Debug 状态",
        "LANG_PON_AUTH_LOG_TIPS1": "PON 进程会输出 Debug 信息到串口 log",
        "LANG_PON_AUTH_LOG_TIPS2": "启用 PON Debug 会影响系统性能",
        "LANG_PON_AUTH_LOG_TIPS3": "不需要 PON Debug 时请及时关闭",
        "LANG_CLEAR_SERIAL_LOG": "清空串口 log",
        "LANG_SERIAL_LOG": "串口日志下载",
        "LANG_CATV_STATUS": "CATV 状态",
        "LANG_SYNC": "同步",
        "LANG_UPTIME": "已连接时间",
        "LANG_WEB_UPTIME":"正常运行时间",
        "LANG_PPPOE_UPTIME": "PPPoE 已连接时间",
        "LANG_STRRSSITHRESHOLD": "错误！无效的 RSSI threshold 数值",
        "LANG_RSSI_THRESHOLD": "关联 RSSI 阀值",
        "LANG_RM_RSSI_THRESHOLD": "移除 RSSI 阀值",
        "LANG_WIRELESS_PERFORMANCE": "无线性能",
        "LANG_WLAN_SCHEDULE_FROM": "起始",
        "LANG_WLAN_SCHEDULE_TO": "截至",
        "LANG_WLAN_SCHEDULE_FOR_HOUR": "（时）",
        "LANG_WLAN_SCHEDULE_FOR_MIN": "（分）",
        "LANG_CONNECTED_TIME": "已连接时间",
        "LANG_CLI_TIMING_FUNC_TIPS": "该功能需打开时间设置中的 SNTP 更新功能，待同步成功后才可使用",
        "LANG_RATE_LIMIT_TIPS": "限速单位：KB/s，0表示不限速",
        "LANG_UPLOAD_LIMIT": "上传限速",
        "LANG_DOWNLOAD_LIMIT": "下载限速",
        "LANG_NOT_SURFING_INTERNET": "禁止上网",
        "LANG_USE_TIME_LIMIT": "使用时间段限制",
        "LANG_START_END_NOT_BE_SAME": "起始时间和截止时间不能一致",
        "LANG_NEED_INTEGER_IN_RANGE": "请输入范围内的整数",
        "LANG_WLAN_CLIENT_MANGEMENT": "WLAN 客户端管理",
        "LANG_ADVANCE_MQTT_CONFIG": "MQTT 配置",
        "CAPUTURE_INSTRUCTION1": "计数模式：抓包数量达 5000 时自动停止",
        "CAPUTURE_INSTRUCTION2": "循环模式：循环覆写捕获文件，抓取大小 3-6 MB",
        "CAPUTURE_INSTRUCTION3": "接口为 Any 时，LAN 侧数据也会被抓取",
        "EXECUTE_REPAIR": "执行修复",
        "PPPoE_DIAG": "PPPoE 服务诊断",
        "DHCP_DIAG": "DHCP 服务诊断",
        "LAN_CONFIG_DIAG": "LAN 配置诊断",
        "INTERNET_CONNECT_DIAG": "互联网连通性诊断",
        "WAN_PARAMS_DIAG": "WAN 配置诊断",
        "PON_DIAG": "PON 诊断",
        "SYS_STATUS_DIAG": "系统状态诊断",
        "LANG_CHOOSE_A_INTERFACE": "请选择一个接口",
        "LANG_DOWNLOAD_CAPTURE_FILE": "下载抓包",
        "LANG_ROTATE": "循环",
        "LANG_COUNT": "计数",
        "LANG_CAPTURE_MODE": "抓包模式",
        "LANG_CAPTURE_PACKETS_ON_WAN": "WAN 侧抓包",
        "WAN_CONNECT_DIAG": "WAN连接状态诊断",
        "PORT_DIAG": "端口诊断",
        "ROUTE_DIAG": "路由诊断",
        "LANG_SELF_DIAGNOSE": "自我诊断",
        "HGU Config": "家庭网关设置",
        "LANG_BASIC_SETTINGS": "基本设置",
        "LANG_STATUS": "状态",
        "HGU Status": "HGU 状态",
        "LANG_DEVICE_INFO": "设备信息",
        "LANG_WAN_CONNECTION_INFO": "网络侧信息",
        "PON_INFO": "PON 信息",
        "LANG_USER_INFO": "客户端信息",
        "LANG_WLAN_SURVERY_INFO": "无线网络信息",
        "LANG_NETWORK": "网络",
        "Network Settings": "网络设置",
        "LANG_WAN": "WAN",
        "LANG_LAN": "局域网",
        "LANG_WLAN": "无线网络",
        "Others": "其它",
        "LANG_BIND": "绑定",
        "LANG_TR069": "远程管理",
        "LANG_QOS": "流量品质",
        "LANG_TIME": "时间",
        "LANG_ROUTER_CONFIG": "路由设置",
        "Advance Settings": "高级设置",
        "LANG_SECURITY": "安全设置",
        "Security Config": "安全配置",
        "LANG_WAN_ACCESS_CONFIG": "WAN 访问设置",
        "LANG_FIREWALL": "防火墙",
        "LANG_MAC_FILTERING": "MAC 地址过滤",
        "LANG_IP_PORT_FILTERING": "IP/Port 过滤设置",
        "LANG_APPLICATION": "应用",
        "Application Config": "应用配置",
        "LANG_VOIP": "宽带电话设置",
        "Multicast Setting": "组播设置",
        "LANG_ADVANCE_NAT_CONFIG": "高级 NAT 设置",
        "LANG_MANAGEMENT": "管理",
        "LANG_USER_MANAGEMENT": "用户管理",
        "LANG_DEVICE_MANAGEMENT": "设备管理",
        "LANG_LOG_FILE_MANAGEMENT": "日志管理",
        "LANG_DIAGNOSTICS": "诊断",
        "Diagnose Tools": "诊断工具",
        "LANG_NETWORK_DIAGNOSTICS": "网络诊断",
        "LANG_LOOPBACK_SET": "环路检测",
        "LANG_HELP": "帮  助",
        "Help Information": "帮助信息",
        "About Network": "关于网络",
        "About Application": "关于应用",
        "Search": "搜索",
        "LANG_LOGOUT": "退出",
        "IPv4 LAN Configuration": "IPv4 LAN 配置",
        "LANG_TIP_ADDR": "IP 地址",
        "LANG_SUBNET_MASK": "子网掩码",
        "Enable DHCP Server": "启用 DHCP 服务器",
        "Start IP Address": "开始 IP 地址",
        "End IP Address": "结束 IP 地址",
        "LANG_LEASE_TIME": "租约时间",
        "LANG_ONE_WEEK": "一周",
        "LANG_ONE_MINUTE": "一分钟",
        "LANG_ONE_HOUR": "一小时",
        "LANG_ONE_DAY": "一天",
        "LAN DNS Mode": "LAN DNS 模式",
        "Primary IP DNS": "首选 IP DNS",
        "Secondary IP DNS": "备用 IP DNS",
        "Enable DHCP Server Relay": "启用 DHCP 服务器中继",
        "DHCP Server IP": "DHCP服务器IP",
        "wan_submit": "应用",
        "LANG_RESERVE_IP_ADDRESS_LIST": "预留 IP 地址列表",
        "LANG_ADD": "添加",
        "IPv6 LAN Configuration": "IPv6 LAN 配置",
        "LANG_IPV6_ADDRESS": "IPv6 地址",
        "IPv6 LAN DNS Mode": "IPv6 LAN DNS 模式",
        "LANG_INTERFACE": "接口",
        "Primary IPv6 DNS": "首选 IPv6 DNS",
        "Secondary IPv6 DNS": "备选 IPv6 DNS",
        "LAN Prefix Delegation": "LAN 前缀授权",
        "IPv6 Prefix : (2001::/64)": "IPv6 前缀（2001::/64）",
        "LANG_DHCPV6": "DHCPv6 设置",
        "DHCPv6 Mode": "DHCPv6 模式",
        "Start IP Address(IPv6)": "开始 IP 地址（IPv6）",
        "End IP Address(IPv6)": "结束 IP 地址（IPv6）",
        "LANG_VALID_LIFETIME": "有效存活时间",
        "LANG_PREFERRED_LIFETIME": "偏好存活时间",
        "RA Configuration": "RA 设置",
        "RA Enable": "RA 启用",
        "LANG_ADVMANAGEDFLAG": "高级管理标志",
        "LANG_ADVOTHERCONFIGFLAG": "高级其余设置标志",
        "LANG_MAXRTRADVINTERVAL": "最大接收时间间隔",
        "LANG_MINRTRADVINTERVAL": "最小接收时间间隔",
        "LANG_DEVICE_BASIC_INFO": "设备基本信息",
        "LANG_DEVICE_MODEL": "设备模型",
        "LANG_DEVICE_SN": "设备标识号",
        "LANG_DEVICE_RESOURCE_INFO": "资源使用信息",
        "LANG_DEVICE_CPUSAGE": "CPU 使用率",
        "LANG_DEVICE_MEMUSAGE": "内存使用率",
        "LANG_HARDWARE_VERSION": "硬件版本",
        "LANG_FIRMWARE_VERSION": "软件版本",
        "LANG_SERIAL_NO": "序列号",
        "IPv4 WAN Info": "IPv4 WAN 信息",
        "LANG_SRV_INTF": "服务接口",
        "LANG_VLAN_ID": "VLAN ID",
        "LANG_PROTOCOL": "协议类型",
        "LANG_IGMP_CONFIG": "IGMP",
        "LANG_IP_ADDRESS": "IP 地址",
        "LANG_MAC_ADDRESS": "MAC 地址",
        "IPv4 Network Info": "IPv4 网络信息",
        "LANG_DEFAULT_GATEWAY": "默认网关",
        "LANG_DNS_FIRST": "首选 DNS",
        "LANG_DNS_SECOND": "备用 DNS",
        "LANG_PREFIX": "前缀",
        "LANG_REMOTE_MANAGEMENT_INFO": "远程管理状态",
        "LANG_TR069_INFO_ADMIN": "远程连接建立状态",
        "LANG_TR069_CONNECT_REQUEST_STATE": "接受 ITMS+ 连接请求情况",
        "LANG_TR069_SERVICE_CONFIG_STATE": "业务配置下发状态",
        "LANG_VOIP_INFO": "宽带语音信息",
        "LANG_PORT_STATE": "端口状态",
        "LANG_PHONE_NUMBER": "电话号码",
        "LANG_ENABLE": "启用",
        "LANG_DISABLE": "禁用",
        "LANG_NO_INFORM": "未上报",
        "LANG_NO_RESPONSE": "上报无回应",
        "LANG_INFORM_BREAK": "上报过程中断",
        "LANG_INFORM_SUCCESS": "上报成功",
        "LANG_INFORM_AUTH_FAIL": "上报验证失败",
        "LANG_INFORMING": "上报中",
        "LANG_NONE": "无",
        "LANG_TR069_NO_REQUEST": "未收到远程连接请求",
        "LANG_TR069_REQUEST_BREAK": "ITMS+ 发起的远程连接过程中断",
        "LANG_TR069_REQUEST_SUCCESS": "ITMS+ 发起的远程连接过程成功",
        "LANG_TR069_NO_SET": "ITMS 未下发远程业务配置状态",
        "LANG_TR069_SETTING": "正在接受 ITMS 的远程业务配置",
        "LANG_TR069_SET_SUCCESS": "业务配置成功",
        "LANG_TR069_SET_FAULT": "业务配置失败",
        "LANG_NET_CONNECT_INFO": "连接信息",
        "LANG_NET_CONNECT_STATE": "连接状态",
        "LANG_FEC_CAPACITY": "FEC 能力",
        "LANG_SUPPORT": "支持",
        "LANG_FEC_UPSTREAM_STATUS": "FEC 上行状态",
        "LANG_FEC_DOWNSTREAM_STATUS": "FEC 下行状态",
        "LANG_ENCRYPT_MODE": "加密模式",
        "LANG_LASER_DEVICE_INFO": "光模块信息",
        "LANG_TX_POWER": "发送功率",
        "LANG_RX_POWER": "接收功率",
        "LANG_TEMPERATURE": "温度",
        "LANG_VOLTAGE": "电压",
        "LANG_BIAS_CURRENT": "偏置电流",
        "LANG_EPON_ALARM_INFO": "PON 告警信息",
        "LANG_LINK_PERFORMANCE_INFO": "链路性能统计信息",
        "LANG_TX_BYTE": "发送字节",
        "LANG_RX_BYTE": "接收字节",
        "LANG_TX_FRAME": "发送帧",
        "LANG_RX_FRAME": "接收帧",
        "LANG_TX_UNICAST_FRAME": "发送单播帧",
        "LANG_RX_UNICAST_FRAME": "接收单播帧",
        "LANG_TX_MULTICAST_FRAME": "发送组播帧",
        "LANG_RX_MULTICAST_FRAME": "接收组播帧",
        "LANG_TX_BROADCAST_FRAME": "发送广播帧",
        "LANG_RX_BROADCAST_FRAME": "接收广播帧",
        "LANG_RX_FEC_ERR_FRAME": "接收 FEC 错误帧",
        "LANG_RX_HEC_ERR_FRAME": "接收 HEC 错误帧",
        "LANG_TX_LOSE_FRAME": "发送丢失帧",
        "LANG_TX_PAUSE_STREAM_CONTROL_FRAME": "发送 PAUSE 流控制帧",
        "LANG_RX_PAUSE_STREAM_CONTROL_FRAME": "接收 PAUSE 流控制帧",
        "LANG_NOT_RESISTERED_NOT_AUTHED": "未注册未认证",
        "LANG_RESISTERED_NOT_AUTHED": "已注册未认证",
        "LANG_RESISTERED_AUTHED": "已注册已认证",
        "WLAN Interface": "WLAN 接口",
        "WLAN Site Survey": "周围 WLAN",
        "SSID-Name": "SSID 名称",
        "SSID Hide": "SSID 隐藏",
        "LANG_ENCRYPTION": "加密",
        "LANG_CHANNEL": "信道",
        "LANG_FLAG": "Flag",
        "LANG_MODE": "模式",
        "LANG_ASSOCIATED_CLIENTS": "接入的无线客户端",
        "LANG_TX_PKT": "发包数",
        "LANG_RX_PKT": "收包数",
        "Send Rate (Mbps)": "发送速率（Mbps）",
        "RSSI (dBm)": "RSSI（dBm）",
        "LANG_POWER_SAVING": "省电模式",
        "LANG_EXPIRED_TIME_SEC": "过期时间（sec）",
        "WLAN Send and Recv": "WLAN 收发包情况",
        "Packets (Recv)": "包（收）",
        "Bytes (Recv)": "字节（收）",
        "Errors (Recv)": "错误（收）",
        "Dropped (Recv)": "丢包（收）",
        "Packets (Send)": "包（发）",
        "Bytes (Send)": "字节（发）",
        "Errors (Send)": "错误（发）",
        "Dropped (Send)": "丢包（发）",
        "LAN Interface": "LAN 接口",
        "LAN Send and Recv": "LAN 收发包情况",
		    "LAN Status": "LAN 状态",
        "LANG_ACTIVE_DHCP_CLIENTS": "活动 DHCP 客户端",
        "LANG_DEVICE_TYPE": "设备类型",
        "LANG_MESH_NEI_MAC": "MAC 地址",
        "WAN Configuration": "WAN 配置",
        "LANG_CONNECTION_NAME": "连接名称",
        "LANG_ADD_NEW_WAN_LINK": "新增 WAN 连接",
        "LANG_IP_VERSION": "IP 版本",
        "Connection Mode:": "连接模式",
        "LANG_ENABLE_VLAN": "启用 VLAN",
        "LANG_VLAN_ID_TITLE": "VLAN ID",
        "pppoe_username": "用户名",
        "pppoe_password": "密码",
        "pppoe_service_name": "服务名称",
        "pppoe_ppptype": "拨号类型",
        "pppoe_continuous": "自动连接",
        "pppoe_connect_on_demand": "按需求连线",
        "LANG_MESH_NEI_IP": "IP 地址",
        "Service Mode:": "服务模式",
        "Disable LAN DHCP:": "禁用 LAN DHCP",
        "binding port": "绑定端口",
        "port_binding_select": "端口选项",
        "port_1": "端口_1",
        "port_2": "端口_2",
        "port_3": "端口_3",
        "port_4": "端口_4",
        "wireless(ssid1-5g)": "无线（AP0-5G）",
        "wireless(ssid2-5g)": "无线（AP1-5G）",
        "wireless(ssid3-5g)": "无线（AP2-5G）",
        "wireless(ssid4-5g)": "无线（AP3-5G）",
        "wireless(ssid5-2.4g)": "无线（AP0-2.4G）",
        "wireless(ssid6-2.4g)": "无线（AP1-2.4G）",
        "wireless(ssid7-2.4g)": "无线（AP2-2.4G）",
        "wireless(ssid8-2.4g)": "无线（AP3-2.4G）",
        "wan_ipv6_address_mode": "WAN IPv6 地址模式",
        "global_ipv6_mode": "DHCP 全局地址获取方式",
        "LANG_STAT_LESS": "无状态自动配置",
        "LANG_MANUAL": "手动",
        "ipv6_dhcp": "DHCP",
        "dhcp_enable_prefix_proxy": "DHCP 启用前缀代理",
        "ds-lite-enable": "DS-Lite 启用",
        "AFTR Address Mode": "AFTR 地址模式",
        "AFTR Address_Domain": "AFTR 地址/域名",
        "ipv6_ip_address": "IPv6 IP 地址",
        "ipv6_gateway": "IPv6 网关",
        "ipv6_request_dns": "Request DNSv6",
        "ipv6_primary_dns": "首选 DNS",
        "ipv6_secondary_dns": "备用 DNS",
        "wan_del": "删除",
        "LANG_NAT_CONFIG": "NAT 设置",
        "2.4g Wlan Basic Setting": "2.4G 无线基础设置",
        "LANG_DISABLE_WLAN_INTERFACE": "禁用无线",
        "LANG_BAND": "频段",
        "LANG_SSID": "SSID 名称",
        "LANG_CANCEL_BROADCAST": "取消广播",
        "LANG_BLOCK_RELAY": "用户隔离",
        "LANG_WMM_SUPPORT": "WMM 支持",
        "LANG_POWER_ENHANCING": "功率增强",
        "LANG_CHANNEL_WIDTH": "频道带宽",
        "LANG_CONTROL_SIDEBAND": "控制边带",
        "LANG_CHANNEL_NUMBER": "信道选择",
        "LANG_AUTO": "自动",
        "LANG_AUTO_WITH_DFS": "自动（DFS）",
        "LANG_AUTO_WITHOUT_DFS": "自动（无DFS）",
        "LANG_RADIO_POWER": "发送功率（%）",
        "LANG_REGDOMAIN": "注册网域",
        "LANG_WPS": "无线网络安全设置",
        "LANG_AUTHENTICATION": "授权",
        "LANG_OPEN_SYSTEM": "开放系统",
        "LANG_SHARED_KEY": "共享密钥",
        "LANG_KEY_LENGTH": "密钥长度",
        "LANG_KEY_FORMAT": "密钥格式",
        "LANG_ENCRYPTION_KEY": "加密密钥",
        "LANG_AUTHENTICATION_MODE": "认证模式",
        "LANG_IEEE_802_11W": "IEEE 802.11w 设置",
        "LANG_SHA256": "SHA256 设置",
        "WPA Cipher Suite": "WPA 密码套件",
        "WPA2 Cipher Suite": "WPA2 密码套件",
        "LANG_GROUP_KEY_UPDATE_TIMER": "定期群组更新",
        "LANG_PRE_SHARED_KEY_FORMAT": "共享密钥格式",
        "LANG_PRE_SHARED_KEY": "预共享密钥",
        "RADIUS Server IP Address": "RADIUS 服务器 IP 地址",
        "RADIUS Server Port": "RADIUS 服务器端口",
        "RADIUS Server Password": "RADIUS 服务器密码",
        "LANG_ADVANCED": "高级设置",
        "LANG_WLAN_MULTIPLE_BSSID_SETTINGS": "无线网络多重 BSSID 设置",
        "5g Wlan Basic Setting": "5G 无线基础设置",
        "LANG_WI_FI_PROTECTED_SETUP": "WPS 设置",
        "LANG_DISABLE_WPS": "关闭 WPS",
        "LANG_SELF_PIN_NUMBER": "本机 PIN 号码",
        "LANG_START_PBC": "开始 PBC",
        "LANG_CLIENT_PIN_NUMBER": "客户端 PIN 号码",
        "LANG_START_PIN": "开始 PIN",
        "LANG_LOGIN": "登录",
        "LANG_USERNAME": "用户名",
        "LANG_PASSWORD": "密码",
        "enter verification code": "输入验证码",
        "wrong user name or password": "用户名或密码错误",
        "VERIFICATION_CODE_IS_NOT_CORRECT_PLEASE_INPUT_THE_PROPER_VERIFICATION_CODE": "错误：验证码验证错误，请重新输入正确的验证码！",
        "LANG_LOGIN_ERROR_3": "错误：连续登录错误 3 次，请等待一段时间后重新登录！",
        "LANG_LOGIN_ERROR_4": "错误：其他用户已登录，同时间只允许一个用户登录！",
        "LANG_LOGIN_ERROR_5": "错误：你已经登录，请注销后再次登录！",
        "LANG_LOGIN_ERROR_6": "错误：网页认证错误，请关闭窗口启重启浏览器再登录！",
        "LANG_FIRMWARE_UPGRADE": "固件升级",
        "LANG_PAGE_DESC_UPGRADE_FIRMWARE": "您可以使用本页面为设备升级一个新的软件版本。请注意，在升级过程中请不要断电，这样可能会使系统崩溃",
        "LANG_CHOOSE_FILE": "选择文件",
        "LANG_UPGRADE": "升级",
        "LANG_RESET": "重置",
        "LANG_SELECTED_FILE_CANNOT_BE_EMPTY": "选定的文件不能为空！",
        "LANG_CANCEL": "取消",
        "LANG_PAGE_DESC_UPGRADE_CONFIRM": "您确定要更新此软件?",
        "LANG_UPGRADE_FAIL_REASON_3": "无效文件",
        "LANG_UPGRADE_FAIL_REASON_1": "文件过大",
        "LANG_UPGRADE_FAIL_REASON_2": "文件格式错误",
        "LANG_DEVICE_RESETTING": "设备重启中，请稍等...",
        "UPLOAD_MODEL_IMAGE_FILE_ERROR": "升级文件对应的设备型号错误",
        "UPLOAD_VENDOR_IMAGE_FILE_ERROR": "升级文件对应的设备供应商不正确",
        "UPLOAD_PONLOCK_IMAGE_FILE_ERROR": "升级文件对应的 PON 锁不正确",
        "UPLOAD_DEFAULT_IMAGE_FILE_ERROR": "升级文件不正确",
        "Upgrade_Success": "升级成功！",
        "LANG_UPLOAD_FAILED": "上传失败",
        "LANG_INACTIVE": "未激活",
        "LANG_NOT_REGISTERED": "未注册",
        "LANG_REGISTERED": "注册成功",
        "LANG_REGISTERING": "注册中",
        "LANG_REGISTER_FAIL": "注册失败",
        "LANG_VOIP_RESTART": "VoIP 重启中...",
        "LANG_ERROR": "错误",
        "LANG_OFF_HOOK": "摘机",
        "LANG_DAIL": "拨号中",
        "LANG_RINGING": "振铃",
        "LANG_RINGBACK": "回铃",
        "LANG_CALL_CONNECTED": "会话中",
        "LANG_REGISTER_FAI": "注册失败",
        "LANG_COMMIT_REBOOT": "提交/重启",
        "LANG_COMMIT_AND_REBOOT": "保存设置及重启路由器",
        "LANG_AUTO_REBOOT": "定时重启",
        "LANG_CURRENT_TIME": "当前时间",
        "LANG_SUN": "星期日",
        "LANG_MON": "星期一",
        "LANG_TUE": "星期二",
        "LANG_WED": "星期三",
        "LANG_THU": "星期四",
        "LANG_FRI": "星期五",
        "LANG_SAT": "星期六",
        "LANG_SYS_SCH_DAY": "设置重启周期",
        "LANG_SYS_SCH_TIME": "设置重启时间",
        "LANG_HOUR": "时",
        "LANG_MIN": "分",
        "LANG_SYNCHRONIZED": "已同步",
        "LANG_UNSYNCHRONIZED": "未同步",
        "LANG_RESET_SETTINGS_TO_DEFAULT": "恢复出厂默认配置",
        "LANG_RESTORE_FACTORY_CONFIGURATION": "恢复出厂配置",
        "LANG_RESTORE_DEFAULT": "恢复默认配置",
        "LANG_DEVICE_MANAGEMENT_HELP_PAGE_0": "配置文件管理",
        "LANG_CONFIG_DOWNLOAD": "下载配置文件",
        "LANG_DOWNLOAD_SUCCESS": "下载成功！",
        "LANG_DEVICE_CURRENT_CONFIG_MANAGEMENT": "当前配置管理",
        "LANG_CONFIG_CURRENT_AS_DEFAULT": "当前配置作为默认配置",
        "LANG_DEVICE_UPLOAD_CONFIG_MANAGEMENT": "导入配置管理",
        "LANG_CONFIG_UPLOAD": "导入配置",
        "LANG_CONFIG_UPLOAD_AS_DEFAULT": "导入为默认配置",
        "LANG_CONFIG_FILE_FINISHED": "配置文件导入完成，请重启设备生效",
        "LANG_UPLOAD_WHEN_END_MAINTAIN": "维护结束上报",
        "LANG_MAINTAIN_PAGE": "点击“维护结束”按纽，系统会自动把新修改的数据上报到服务器。",
        "LANG_END_MAINTAIN": "维护结束",
        "LANG_MAINTAIN_ERR_1": "成功：通知 ITMS 维护已经结束！",
        "LANG_MAINTAIN_ERR_2": "错误：找不到 TR069 程序！",
        "LANG_CANCLE_SETTING_DEFAULT": "取消自定义默认配置",
        "LANG_DISABLED": "关闭",
        "LANG_ENABLED": "启动",
        "LANG_VISIBLE": "可见",
        "LANG_HIDDEN": "隐藏",
        "LANG_WLAN_EASY_MESH_DEVICE_DETAILS": "EasyMesh 设备详细列表",
        "LANG_WLAN_EASY_MESH_STA_INFO": "设备列表",
        "LANG_REFRESH": "刷新",
        "LANG_NODE_INFO": "节点信息",
        "LANG_INVALID_MTU_VALUE_YOU_SHOULD_SET_A_VALUE_BETWEEN_650_1500": "无效的 MTU 值！您应该设置一个 650-1500 之间的值。",
        "LANG_INVALID_MTU_VALUE_YOU_SHOULD_SET_A_VALUE_BETWEEN_650_1492": "无效的 MTU 值！您应该设置一个 650-1492 之间的值。",
        "LANG_INVALID_VLAN_RANGE": "输入错误，请输入小于 4096 的正整数，但不包括",
        "LANG_IS_INVALID": "是无效的",
        "LANG_TRY_AGAIN": "请重新输入",
        "LANG_PPP_USER_NAME_CANNOT_BE_EMPTY": "PPP 账号不能是空！",
        "LANG_SERVICE_NAME": "服务名称",
        "LANG_INVALID_SECONDARY_IPV6_DNS_ADDRESS": "备用 IPv6 DNS 地址无效！",
        "LANG_INVALID_PRIMARY_IPV6_DNS_ADDRESS": "主 IPv6 DNS 地址无效！",
        "LANG_INVALID_IPV6_GATEWAY_ADDRESS": "IPv6 网关地址无效！",
        "LANG_INVALID_IPV6_PREFIX_LENGTH": "IPv6 前置长度无效！",
        "LANG_INVALID_IPV6_ADDRESS": "IPv6 地址无效！",
        "LANG_SHOULD_NOT_BE_EMPTY": "不应该为空",
        "LANG_CONFIG": "设置",
        "LANG_PORT_BINDING_EXIST": "一个端口只能绑定一个 WAN 配置",
        "LANG_STRCONNECTEXIST": "连线已存在！",
        "LANG_BIND_PORT": "绑定端口",
        "LANG_IPV6_PREFIX_LENGTH": "IPv6 前缀长度",
        "LANG_BRIDGE_IGMP": "透传组播",
        "LANG_GLOBAL_IP_MODE": "全局地址获取方式",
        "LANG_PPP_TYPE": "拨号模式",
        "LANG_PLEASE_INPUT_IPV6_ADDRESS_OR_SELECT_DHCPV6_CLIENT_OR_CLICK_SLAAC": "请输入 IPv6 地址，或选择 DHCPv6 Client/SLAAC！",
        "LANG_PPP_PASSWORD_CANNOT_BE_EMPTY": "PPP 密码不能是空的！",
        "LANG_STRMAXVC": "错误：超过 VC 最大数量！",
        "LANG_STRTABLEFULL": "错误！表格已满。",
        "LANG_STRMAXNUMPPPOE": "已超过这个 VC 的 PPPoE 连接最大数量！",
        "LANG_STRADDCHAINERROR": "新增 chain 纪录错误！",
        "LANG_ADDRESS": "地址",
        "LANG_START": "开始",
        "LANG_END": "结束",
        "LANG_END_ADDRESS_MUST_BIG_THANSTART_ADDRESS": "终止 IP 地址必须等于或大于初始 IP 地址",
        "LANG_SERVER": "服务器",
        "LANG_INVALID_MAC_ADDR_SHOULD_NOT_EMPTY": "MAC 地址不能为空。",
        "LANG_IP_ADDRESS_CANNOT_BE_EMPTY": "IP 地址不能为空！",
        "LANG_RESERVED_ADDRESS_ALERT": "保留地址应在 DHCP 地址范围内",
        "LANG_INVALID_LAN_IPV6_IP": "LAN IPv6 IP 无效！",
        "LANG_INVALID_6RD_PREFIX_ADDRESS": "6rd 前置地址无效！",
        "LANG_INVALID_6RD_PREFIX_LENGTH": "6rd 前置长度无效！",
        "LANG_START_IP_ADDRESS_CANNOT_BE_EMPTY_FORMAT_IS_IPV6_ADDRESS_FOR_EXAMPLE_2000_0200_10": "起始 IP 地址不能为空！格式为 IPv6 地址（2000:0200:0000:0010）",
        "LANG_INVALID_START_IP": "无效起始 IP！格式为 IPv6 地址（2000:0200:0000:0010）",
        "LANG_END_IP_ADDRESS_CANNOT_BE_EMPTY_FORMAT_IS_IPV6_ADDRESS_FOR_EXAMPLE_2000_0200_20": "结束 IP 地址不能为空！格式为 IPv6 地址（2000:0200:0000:0020）",
        "LANG_INVALID_END_IP": "无效结束 IP！格式为 IPv6 地址（2000:0200:0000:0020）",
        "LANG_INVALID_MAXRTRADVINTERVAL_IT_SHOULD_BE_THE_DECIMAL_NUMBER_0_9": "无效的 MaxRtrAdvInterval！它应该是十进制数字（0-9）",
        "LANG_MAXRTRADVINTERVAL_MUST_BE_NO_LESS_THAN_4_SECONDS_AND_NO_GREATER_THAN_1800_SECONDS": "MaxRtrAdvInterval 必须不小于 4 秒且不大于 1800 秒。",
        "LANG_INVALID_MINRTRADVINTERVAL_IT_SHOULD_BE_THE_DECIMAL_NUMBER_0_9": "无效的 MinRtrAdvInterval！它应该是十进制数字（0-9）",
        "LANG_MINRTRADVINTERVAL_MUST_BE_NO_LESS_THAN_3_SECONDS_AND_NO_GREATER_THAN_0_75_MAXRTRADVINTERVAL": "MinRtrAdvInterval 必须不小于 3 秒且不大于 0.75 * MaxRtrAdvInterval。",
        "LANG_INVALID_LAN_IPV6_PREVIX": "无效的LAN IPv6 Previx！",
        "LANG_SSID_CANNOT_BE_EMPTY": "SSID 不能为空！",
        "LANG_BROADCAST": "广播",
        "LANG_DATA_RATE": "速率",
        "LANG_CONFIGURATION": "设置",
        "LANG_FRAGMENT_THRESHOLD": "分片阀值",
        "LANG_BEACON_INTERVAL": "信号回报间隔",
        "LANG_PREAMBLE_TYPE": "前导信号类型",
        "LANG_SHORT_PREAMBLE": "短前导信号",
        "LANG_LONG_PREAMBLE": "长前导信号",
        "LANG_INVALID_VALUE_IT_SHOULD_BE_IN_DECIMAL_NUMBER_0_9": "无效的值。它应该在十进制数字（0-9）。",
        "LANG_INVALID_VALUE_OF_FRAGMENT_THRESHOLD_INPUT_VALUE_SHOULD_BE_BETWEEN_256_2346_IN_DECIMAL": "Fragment Threshold 无效。输入的值应介于 256-2346。",
        "LANG_INVALID_VALUE_OF_RTS_THRESHOLD_INPUT_VALUE_SHOULD_BE_BETWEEN_0_2347_IN_DECIMAL": "RTS Threshold 无效。输入的值应介于 0-2347。",
        "LANG_INVALID_VALUE_OF_BEACON_INTERVAL_INPUT_VALUE_SHOULD_BE_BETWEEN_20_1024_IN_DECIMAL": "Beacon Interva 无效。输入的值应介于 20-1024。",
        "LANG_RTS_THRESHOLD": "RTS阀值",
        "LANG_PROTECTION": "保护",
        "LANG_AGGREGATION": "聚集",
        "LANG_SHORT_GI": "缩短保护间隔（GI）",
        "LANG_DOT11K_SUPPORT": "802.11k 支持",
        "LANG_DOT11V_SUPPORT": "802.11v 支持",
        "LANG_START_PBC_MSG": "成功启动 PBC！\n\n您须在两分钟内在客户端开启 WPS。",
        "LANG_START_PIN_MSG": "成功启动 PIN！\n\n您须在两分钟内在客户端开启 WPS。",
        "LANG_INVALID_PIN_LENGTH_THE_DEVICE_PIN_IS_USUALLY_FOUR_OR_EIGHT_DIGITS_LONG": "PIN 的长度无效！设备 PIN 通常是 4 个 或 8 个数字长。",
        "LANG_INVALID_PIN_THE_DEVICE_PIN_MUST_BE_NUMERIC_DIGITS": "PIN 无效！设备 PIN 必须是数字。",
        "LANG_INVALID_PIN_CHECKSUM_ERRO": "PIN 无效！校验和错误。",
        "LANG_WLAN_SECURITY_SETTINGS": "无线网络安全设置",
        "LANG_DEVICE_NAME": "设备名称",
        "LANG_CONTROLLER": "控制设备",
        "LANG_WLAN_EASY_MESH_DEVICE_NAME_CANNOT_BE_EMPTY": "设备名称不能为空",
        "LANG_WLAN_EASY_MESH_11KV_ENABLE_WARNING_MESSAGE": "11k 和 11v 没有开启，点击开启以继续",
        "LANG_WLAN_EASY_MESH_ALERT_VAP1_AUTO_MANAGED_MESSAGE": "注意，5G 和 2.4G 的第一个虚拟 AP 将被自动管理，请点击继续。",
        "LANG_STA_NUMBER": "限制客户数",
        "LANG_CIPHER_SUITE": "密码选项",
        "LANG_ILLEGAL_CHARACTER": "存在非法字符",
        "LANG_INVALID_LENGTH_OF_KEY_VALUE": "关键值的长度无效。",
        "LANG_PORT_RANGE_CANNOT_BE_EMPTY_YOU_SHOULD_SET_A_VALUE_BETWEEN_1_65535": "端口范围不能为空！您应设置 1-65535 之间的一个值。",
        "LANG_PRE_SHARED_KEY_VALUE_SHOULD_BE_SET_AT_LEAST_8_CHARACTERS": "预共享的密钥值应设置至少 8 个字符。",
        "LANG_WPA_CIPHER_SUITE_CAN_NOT_BE_EMPTY": "WPA 密码选项不能为空。",
        "LANG_WPA2_CIPHER_SUITE_CAN_NOT_BE_EMPTY": "WPA2 密码选项不能为空。",
        "LANG_PRE_SHARED_KEY_VALUE_SHOULD_BE_64_CHARACTERS": "预共享的密钥值应为 64 个字符。",
        "LANG_USERNAME_TITLE": "原用户名",
        "LANG_OLD_PASSWORD_TITLE": "旧密码",
        "LANG_NEW_PASSWORD_TITLE": "新密码",
        "LANG_AFFIRM_PASSWORD_TITLE": "确认密码",
        "LANG_PSWD_SHOULD_NOT_BE_SAME": "新密码不应与旧密码相同！",
        "LANG_PSWD_IS_INVALID": "新密码不允许使用，请重新修正再试一次！",
        "LANG_ERROR_INPUT_OLD_USER_PASSWORD_ERROR": "错误：输入旧密码错误！",
        "LANG_SUBMIT_SUCCESS": "应用成功",
        "LANG_PASSWORD_CANNOT_BE_EMPTY_PLEASE_TRY_IT_AGAIN": "密码不能为空。请再试一次。",
        "LANG_NEW_PASSWORD_CAN_NOT_BE_EMPTY_INPUT_AGAIN": "新密码不能为空，请输入新密码！",
        "LANG_NEW_PASSWORD_ERROR_INPUT_PASSWORD_AGAIN": "新密码错误，请重新输入新密码！",
        "LANG_MGM_USER_PASSWORD_RULE1": "需要设置的密码不可少于 6 个字符",
        "LANG_MGM_USER_PASSWORD_RULE2": "需要设置的密码不可多于 16 个字符",
        "LANG_MGM_USER_PASSWORD_RULE3": "需要设置的密码需包含以下两种以上的字符格式：",
        "LANG_MGM_USER_PASSWORD_RULE4": "0-9、a-z、A-Z、特殊字符（. _ / @ ! ~ # $ % ^ * ( ) + : ?）。",
        "LANG_AFFIRM_PASSWORD_CAN_NOT_BE_EMPTY_INPUT_AGAIN": "确认密码不能为空，请输入确认密码！",
        "LANG_AFFIRM_PASSWORD_DO_NOT_MATCH_NEW_PASSWORD_INPUT_AGAIN": "新密码和确认密码不匹配，请重新输入确认密码！",
        "LANG_BIND_MODE": "绑定模式",
        "LANG_PORT": "端口",
        "LANG_INVALID_VLAN_ID": "VLAN ID 无效！",
        "LANG_INVALID_VLAN_RANGE2": "请输入小于 4096 的正整数",
        "LANG_VLAN_ID_IS_RESERVED": "VLAN ID 系统保留！",
        "LANG_NET_VLAN_MAPPING_ERR_3": "VLAN ID 对不允许重复，请重新输入。",
        "LANG_NET_VLAN_MAPPING_ERR_1": "VLAN ID 必须成对填写，请重新输入。",
        "LANG_BIND_CONFIG": "绑定设置",
        "LANG_TR069_CLIENT_CONFIGURATION": "TR069 客户配置",
        "LANG_SERVER_URL": "服务器 URL",
        "LANG_ENABLE_CERTIFICATE": "启用证书",
        "LANG_PERIODIC_REPORT": "周期上报",
        "LANG_PERIODIC_REPORT_INTERVAL": "周期上报时间间隔",
        "LANG_CONNECT_REQUEST_USERNAME": "连接请求用户名",
        "LANG_CONNECT_REQUEST_PASSWORD": "连接请求密码",
        "LANG_LLID_CONFIG": "逻辑 ID 设置",
        "LANG_PLOAM_CONFIG": "PonPwd 设置",
        "LANG_TRUSTED_CA_CERTIFICATE": "受信任的权威认证（CA）证书",
        "LANG_CERTIFICATE_IMPORT": "证书导入",
        "LANG_DELETE_CERT": "删除已上传证书",
        "LANG_UPLOAD_SUCCESS": "上传成功！",
        "LANG_DELETE_SUCCESS": "删除成功！",
        "LANG_NET_TR069_ERROR_1": "ACS URL 是不合法的 URL！",
        "LANG_NET_TR069_ERROR_2": "周期上报间隔时间必须为正整数！",
        "LANG_NET_TR069_ERROR_3": "ACS 用户名含有非法字符，请重新输入！",
        "LANG_NET_TR069_ERROR_4": "ACS 密码含有非法字符，请重新输入！",
        "LANG_NET_TR069_ERROR_5": "连接请求用户名含有非法字符，请重新输入！",
        "LANG_NET_TR069_ERROR_6": "连接请求密码含有非法字符，请重新输入！",
        "LANG_LLID_CONFIG_ERR_1": "存在无效字符或长度不在 1-24 字节之间，请重新输入！",
        "LANG_TIMER_CONFIG": "时间管理",
        "LANG_TIME_ZONE_SELECT": "时区选择",
        "LANG_ENABLE_DAYLIGHT_SAVING_TIME": "启用夏令时",
        "LANG_ENABLE_SNTP_CLIENT_UPDATE": "启用SNTP Client更新",
        "LANG_PRIMARY": "首选",
        "LANG_STANDBY": "备用",
        "LANG_SYNCHRONIZING_TYPE": "同步通道",
        "LANG_SYNCHRONIZING_WAN_INTERFAVE": "同步 WAN 连接",
        "LANG_INTERVAL": "间隔",
        "LANG_NTP_SERVER_OTHER1": "首选 ntp 服务器选择 other，但是 other 为空",
        "LANG_NTP_SERVER_OTHER2": "第二 ntp 服务器选择 other，但是 other 为空",
        "LANG_INTERVAL_SHOULD_NOT_BE_0": "同步间隔不可以为零",
        "LANG_RIP": "RIP 设置",
        "LANG_INPUT_CONFIGURATION": "请输入配置",
        "LANG_RECEIVE_MODE": "接收模式",
        "LANG_SEND_MODE": "传送模式",
        "LANG_DELETE_SELECTED": "删除所选",
        "LANG_DELETE_ALL": "全部删除",
        "LANG_ENTRY_ALREADY_EXISTS": "条目已存在！",
        "LANG_THERE_IS_NO_ITEM_SELECTED_TO_DELETE": "没有选择要删除的项目！",
        "LANG_STATIC_ROUTER": "静态路由",
        "LANG_DESTINATION": "目的",
        "LANG_GATEWAY": "网关",
        "LANG_METRIC": "量测",
        "LANG_SHOW_ROUTES": "显示路由",
        "LANG_IP_ROUTE_TABLE": "IP 路由表",
        "LANG_THE_SPECIFIED_MASK_PARAMETER_IS_INVALID_DESTINATION_MASK_DESTINATION": "指定的掩码参数是无效的。（目的地址 & 掩码）!= 目的地。",
        "LANG_CHECK_IP_ERR_1": "IP地址不能是空的！格式为 xxx.xxx.xxx.xxx。",
        "LANG_CHECK_IP_ERR_2": "IP地址无效，必须是 0-9 的数值。",
        "LANG_CHECK_IP_ERR_3": "IP地址无效。",
        "LANG_CHECK_IP_ERR_4": "IP地址的第一组无效，必须是 1-223 的数值。",
        "LANG_CHECK_IP_ERR_5": "IP地址的第二组无效，必须是 0-255 的数值。",
        "LANG_CHECK_IP_ERR_6": "IP地址的第三组无效，必须是 0-255 的数值。",
        "LANG_CHECK_IP_ERR_7": "IP地址的第四组无效，必须是 0-254 的数值。",
        "LANG_INVALID_IPV4_SUBNET_SHOULD_NOT_EMPTY": "子网掩码地址不能为空白！为 xxx.xxx.xxx.xxx 格式。",
        "LANG_INVALID_IPV4_SUBNET_SHOULD_BE_DECIMAL_NUM": "不正确的子网掩码地址，应该要为十进位数值（0-9）",
        "LANG_INVALID_IPV4_SUBNET_DIGIT": "不正确的子网掩码数值，应该要为以下其中之一 0、128、192、224、240、248、252、254。",
        "LANG_ENTER_NEXT_HOP_IP_OR_SELECT_A_GW_INTERFACE": "输入网关 IP 或选择一个 GW 接口！",
        "LANG_INVALID_METRIC_RANGE_IT_SHOULD_BE_0_16": "Metric 范围无效。它应为 0-16。",
        "LANG_VOIP_HELP_PAGE_2": "宽带电话基本设置",
        "LANG_SERVER_TYPE": "软交换版本",
        "LANG_PRIMARY_SIP_REG": "主 SIP 注册",
        "LANG_REGISTER": "注册",
        "LANG_PROXY": "代理",
        "LANG_SUBSCRIBE": "订阅",
        "LANG_OUTBOUND": "外发",
        "LANG_START_PORT": "起始端口",
        "LANG_EXPIRE": "有效期（秒）",
        "LANG_LOCAL": "本地",
        "LANG_USER_NUMBER": "用户号码",
        "LANG_USER_LOGIN": "用户账号",
        "LANG_USER_PASSWORD": "用户密码",
        "LANG_PACKET_TIME": "打包时长",
        "LANG_VOIP_ADVANCE_CONFIG": "宽带电话高级设置",
        "LANG_VOIP_BASIC_CONFIG": "宽带电话基本设置",
        "LANG_LEC": "回声消除设置",
        "LANG_SYNC_PHONE_TIME": "同步话机时间",
        "LANG_CALLER_ID_MODE": "来电显示模式",
        "LANG_REGION": "区域",
        "LANG_VOIP_HB_PASSIVE_OPTION": "Option 被动",
        "LANG_VOIP_HB_ACTIVE_REGISTER": "Register 主动",
        "LANG_VOIP_HB_ACTIVE_OPTION": "Option 主动",
        "LANG_HEART_BEAT_CYCLE": "心跳时间（秒）",
        "LANG_NO_ANSWER_TIMER": "久叫不应",
        "LANG_SEND_GAIN": "发送增益",
        "LANG_RECV_GAIN": "接收增益",
        "LANG_USER_ACCOUNT": "账号",
        "LANG_FLASH_TIME": "拍叉时间",
        "LANG_DAIL_PLAN_ENABLE": "数图启用",
        "LANG_MAX_MATCH": "数图最大匹配模式",
        "LANG_ENCODE_HASH": "转码'#'",
        "LANG_DAIL_PLAN": "数图",
        "LANG_CODEC": "编码",
        "LANG_LINE": "线路",
        "LANG_PRIORITY": "优先级",
        "LANG_SESSION_EXPIRE_SEC": "会议层超时（秒）",
        "LANG_FLASH_HOOK_TIME": "拍叉时间设置（毫秒，10 的整数倍，最小：80，最大：2000）",
        "LANG_OFF_HOOK_ALARM": "摘机不拨号时间",
        "LANG_SHORT_DIGIT_TIMER": "位间短定时器（秒）",
        "LANG_LONG_DIGIT_TIMER": "位间长定时器（秒）",
        "LANG_BUSY_TONE_TIME": "播放忙音时间（秒）",
        "LANG_HOWLER_TIME": "播放催挂音时间（秒）",
        "LANG_REG_RETRY_INTERVAL": "注册重试时间",
        "LANG_HEART_BEAT_MODE": "心跳模式",
        "LANG_POLAR_REVERSAL": "极性反转",
        "LANG_CALL_WAIT": "呼叫等待",
        "LANG_3PTY_CONFERENCE": "三方通话",
        "LANG_HOT_LINE_ENABLE": "启用热线",
        "LANG_HOT_LINE_TIMEOUT": "热线超时",
        "LANG_HOT_LINE_NUMBER": "热线号码",
        "LANG_UNCOND_FORWARD": "无条件转移",
        "LANG_UNCOND_NUM": "无条件转移号码",
        "LANG_BUSY_FORWARD": "遇忙转移",
        "LANG_BUSY_FORWARD_NUM": "遇忙转移号码",
        "LANG_NO_ANSWER_FORWARD": "无应答转移",
        "LANG_NO_ANSWER_FORWARD_NUM": "无应答转移号码",
        "LANG_NO_ANSWER_FORWARD_TIME": "无应答转移时间",
        "LANG_CALL_TRANSFER": "呼叫后转",
        "LANG_UNATTEND_TRANSFER": "盲转（E、F、0-9）",
        "LANG_ATTEND_TRANSFER": "询问转（E、F、0-9）",
        "LANG_INVALID": "不正确",
        "LANG_NEED_ACCOUNT": "需启用线路账号",
        "LANG_APP_VOIP_ERR": "线路1号码与线路2号码相同",
        "LANG_APP_VOIP2_ERR": "宽带电话高级设置错误，相同设置在不同优先顺序！",
        "LANG_DOMAIN": "域名",
        "LANG_ALG": "应用防火墙（ALG）",
        "LANG_DMZ_HOST_TITLE": "DMZ 主机",
        "LANG_DMZ_IP_ADDRESS_TITLE": "DMZ 主机 IP 地址",
        "LANG_NAT_DMZ_HOST": "DMZ 主机",
        "LANG_NAT_VIRTUAL_SERVER_CONFIGURATION": "虚拟服务器设置",
        "LANG_EXTERNAL_IP_ADDRESS": "外部 IP 地址",
        "LANG_EXTERNAL_START_PORT": "外部初始端口",
        "LANG_EXTERNAL_END_PORT": "外部终止端口",
        "LANG_SERVER_IP_ADDR": "服务器 IP 地址",
        "LANG_SOURCE_PORT": "源端口",
        "LANG_SERVER_NAME": "服务器名",
        "LANG_DYNAMIC_DNS_2": "动态 DNS",
        "LANG_ENABLE_DDNS_SERVICE": "启用动态 DNS 服务",
        "LANG_HOSTNAME": "主机名称",
        "LANG_SERVICE": "服务",
        "LANG_ADD_DYNAMIC_DNS": "添加动态 DNS",
        "LANG_ORAY_COM": "花生壳（oray.com）",
        "LANG_DDNS_PROVIDER": "DDNS 提供者",
        "LANG_EMAIL": "电子信箱",
        "LANG_KEY": "密钥",
        "LANG_ADD_DDNS_ERR_1": "请输入合法的主机名",
        "LANG_ADD_DDNS_ERR_2": "请输入合法的用户名",
        "LANG_ADD_DDNS_ERR_3": "请输入合法的密码",
        "LANG_INVALID_EMAIL": "无效的电子邮件。",
        "LANG_INVALID_KEY": "无效的密钥。",
        "LANG_UPNP_CONFIG": "UPnP 设置",
        "LANG_RSTBTN_CONFIG": "硬件复位设置",
        "LANG_RSTBTN_SWITCH": "阻止硬件复位按钮",
        "LANG_IGMP_SNOOPING_CONFIG": "IGMP Snooping 设置",
        "LANG_IGMP_PROXY": "IGMP 代理",
        "LANG_INTERNET_CONNECTION": "因特网连接",
        "LANG_MLD_SNOOPING_CONFIG": "MLD Snooping",
        "LANG_MLD_PROXY": "MLD 代理",
        "LANG_MCAST_VLAN": "组播 VLAN",
        "LANG_MULTICAST_VLAN_TITLE": "组播 VLAN（空白表示不设置）",
        "LANG_SYSTEM_LOG": "系统日志",
        "LANG_RECORD_TITLE": "记录",
        "LANG_RECORD_LEVEL_TITLE": "记录等级",
        "LANG_DISPLAY_LEVEL_TITLE": "显示等级",
        "LANG_NAT_CONFIG_HELP_PAGE_VIRTUAL_6": "服务器 IP 地址",
        "LANG_SERVER_UDP_PORT_TITLE": "服务器 UDP 端口",
        "LANG_DEVICE_LOG": "设备日志",
        "LANG_DOWNLOAD_LOG": "日志下载",
        "LANG_CLEAR_RECORDS": "清除记录 ",
        "LANG_SYSTEM_ACCESS_LOG": "系统访问日志",
        "LANG_DATE_TIME": "日期/时间",
        "LANG_SEVERITY": "严重程度",
        "LANG_INFO": "信息",
        "LANG_ACCESS_RECORDS": "访问记录",
        "LANG_SYS_LOG_ALERT0": "没有记录条目。",
        "LANG_SERVER_UDP_PORT": "服务器 UDP 端口",
        "LANG_SYSLOG_CONFIGURATION_PAGE_1": "如果记录模式已启用，系统将开始记录所有已选择的事件。对于记录的等级，所有与已选等级相等或更高等级的事件将被记录。",
        "LANG_SYSLOG_CONFIGURATION_PAGE_2": "对于显示的等级，所有与已选等级相等或更高等级的事件将被显示。",
        "LANG_SYSLOG_CONFIGURATION_PAGE_3": "如果选择的模式是“Remote”或“Both”，事件将被送到远程系统记录服务器的特定 IP 地址和 UDP 端口。",
        "LANG_SYSLOG_CONFIGURATION_PAGE_4": "如果选择的模式是“Local”或“Both”，事件将被记录在本地存储器。",
        "LANG_SYSLOG_CONFIGURATION_PAGE_5": "选择需要的值，然后点击“保存/应用”来配置系统记录选项。",
        "LANG_DESTINATION_ADDRESS": "目标地址",
        "LANG_WAN_INTERFACE": "WAN 接口",
        "LANG_PING_TEST": "PING 测试",
        "LANG_TRACERT_TEST": "Tracert 测试",
        "LANG_PING_ERR_1": "目标地址或者 WAN 接口不正确！",
        "LANG_PING_ERR_2": "没有找到相应的 WAN 接口！",
        "LANG_PLEASE_WAIT": "请稍等...",
        "LANG_PING_TEST_FAILED": "PING 测试失败！",
        "LANG_RESULT": "结果",
        "LANG_TRACERT_ERR_1": "地址不正确！",
        "LANG_TRACERT_ERR_2": "Tracert 测试失败",
        "LANG_TR069_INFORM": "手动上报 Inform",
        "LANG_LOOPBACK_TEST": "环路检测",
        "LANG_ENABLE_LOOPBACK_DETECTION": "环路检测使能",
        "LANG_DETECTION_FRAME_INTERVAL": "检测报文间隔",
        "LANG_RECOVER_FRAME_INTERVAL": "恢复报文间隔",
        "LANG_ETHERTYPE": "以太网类型",
        "LANG_PORT_LOOPBACK_DETECT_STATE": "端口环路检测状态",
        "LANG_NO_LOOPBACK": "无环路",
        "LANG_LOOPBACK_DETECTE_RESULT_1": "检测到环路并已关闭端口",
        "LANG_LOOPBACK_DETECTE_RESULT_2": "检测到环路但未能关闭端口",
        "LANG_LOOPBACK_DETECTE_ERR_1": "检测报文间隔只接受 1-60 秒！",
        "LANG_LOOPBACK_DETECTE_ERR_2": "恢复报文间隔只接受 10-1800 秒！",
        "LANG_LOOPBACK_DETECTE_ERR_3": "以太网类型必须为十六进制值！",
        "LANG_LOOPBACK_DETECTE_ERR_4": "必须指定 VLAN 值！",
        "LANG_LOOPBACK_TEST_PAGE": "以“,”隔开，0 代表 untagged（如：0,45,46）",
        "LANG_URL_FILTER_ENABLE": "开启 URL 过滤",
        "LANG_URL_FILTER": "URL 过滤",
        "LANG_FILTER_MODE": "过滤模式",
        "LANG_BLACK_LIST": "黑名单",
        "LANG_WHITE_LIST": "白名单",
        "LANG_FILTER_RULE_LIST": "过滤规则列表",
        "LANG_LIST_LIMIT": "最多添加 100 条规则",
        "LANG_INVALID_URL_ADDR_SHOULD_NOT_EMPTY": "URL 地址不能为空",
        "LANG_URL_ADDRESS": "URL 地址",
        "LANG_RULE_ALREADY_EXISTS": "规则已存在！",
        "LANG_MAX_RULES": "达到最大规则数",
        "LANG_ADD_REEOR": "添加失败",
        "LANG_DELETE_ERROR": "删除失败",
        "LANG_SELECT_FIREWALL_LEVEL": "选择防火墙等级",
        "LANG_LOW": "低",
        "LANG_HIGH": "高",
        "LANG_SECURITY_CLASSIFY": "安全级别设置",
        "LANG_ATTACK_PROTECTION_CONFIG": "攻击保护设置",
        "LANG_WHITE_LIST_COMMENT": "不支持桥接模式下的 MAC 地址过滤。请添加 MAC 后再应用白名单。",
        "LANG_MAC_FILTER_ENABLE": "开启 MAC 地址过滤",
        "LANG_WHITELIST_CTRL": "白名单列表已清空，请切换成黑名单或者关闭 MAC 过滤",
        "LANG_COMMON_PORT_FILTERING": "常用端口过滤",
        "LANG_FILTERING": "过滤",
        "LANG_IP_FILTER_FUNCTION_DESCRIPTION": "你可以通过提交键来开启或者关闭 IP/Port 过滤的功能。当白名单不为空的时候，设备工作在白名单模式，否则工作在黑名单模式。",
        "LANG_UPSTREAM": "上行流",
        "LANG_BLACK_LIST_NOTE": "黑名单开启时，默认允许所有 LAN 侧来的上行流，可以添加黑名单规则来阻止特定流",
        "LANG_WHITE_LIST_NOTE": "白名单开启时，默认阻止所有 WAN 侧来流，添加白名单规则来允许特定的流下来",
        "LANG_RSTBTN_NOTE": "此按钮开启时，硬件复位按钮被阻止使用",  
        "LANG_NAME": "名称",
        "LANG_SOURCE": "源",
        "LANG_DESTINATION_PORT": "目的端口",
        "LANG_ADD_IP_FILTER_OUT": "添加 IP/Port 过滤器（流出）",
        "LANG_ADD_IP_FILTER_INCOMING": "添加 IP/Port 过滤器（流入）",
        "LANG_FILTER_NAME": "过滤器名",
        "LANG_PREFIX_LENGTH": "前置长度",
        "LANG_START_ADDRESS": "起始地址",
        "LANG_END_ADDRESS": "结束地址",
        "LANG_MAX_VIRTUAL_SERVER_RULES": "对不起，规则数已达最大限制",
        "LANG_SETTING_ERROR": "设置错误！",
        "LANG_FILTER_ADD_ERROR_2": "源 IP 结束地址必须搭配源 IP 起始地址",
        "LANG_FILTER_ADD_ERROR_3": "目的 IP 结束地址必须搭配目的 IP 起始地址",
        "LANG_FILTER_ADD_ERROR_4": "源子网掩码必须搭配源 IP 地址",
        "LANG_FILTER_ADD_ERROR_5": "目的子网掩码必须搭配目的 IP 地址",
        "LANG_FILTER_ADD_ERROR_8": "源 IP 起始地址不能大于结束地址",
        "LANG_FILTER_ADD_ERROR_9": "设置源 IP 范围时不能填入源子网掩码",
        "LANG_FILTER_ADD_ERROR_11": "目的 IP 起始地址不能大于结束地址",
        "LANG_FILTER_ADD_ERROR_12": "设置目的 IP 范围时不能填入目的子网掩码",
        "LANG_INVALID_SOURCE_IPV6_PREFIX_LENGTH": "无效的源 IPv6 前缀长度！",
        "LANG_INVALID_SOURCE_IPV6_END_ADDRESS": "无效的源 IPv6 结束地址！",
        "LANG_INVALID_DESTINATION_IPV6_START_ADDRESS": "无效目标 IPv6 起始地址！",
        "LANG_INVALID_DESTINATION_IPV6_PREFIX_LENGTH": "无效的目标 IPv6 前缀长度！",
        "LANG_INVALID_DESTINATION_IPV6_END_ADDRESS": "无效目标 IPv6 结束地址！",
        "LANG_FILTER_ADD_ERROR_1": "端口号必须与 TCP 或 UDP 一起选择",
        "LANG_FILTER_ADD_ERROR_6": "结束源端口必须搭配起始源端口",
        "LANG_FILTER_ADD_ERROR_7": "结束目的端口必须搭配起始目的端口",
        "LANG_SOURCE_START_PORT": "源起始端口",
        "LANG_SOURCE_END_PORT": "源结束端口",
        "LANG_FILTER_ADD_ERROR_10": "源起始端口不能大于结束端口",
        "LANG_DESTINATION_START_PORT": "目的起始端口",
        "LANG_DESTINATION_END_PORT": "目的结束端口",
        "LANG_FILTER_ADD_ERROR_13": "目的起始端口不能大于结束端口",
        "LANG_FILTER_ADD_ERROR_14": "请设置过滤规则",
        "LANG_REMOTE_HOST": "远端主机",
        "LANG_PLEASE_SELECT_AN_ENTRY_TO_DELETE": "请选择删除一个的项目！",
        "LANG_URL_FILTER_NOTE": "URL 不需要添加 HTTP 和 WWW 头，如过滤 http://www.example.com，只需输入 example.com",
        "LANG_THE_MAXIMUM_NUMBER_OF_ENTRIES_ARE_16": "项目最大值为 16",
        "LANG_ENTRY_EXIST": "条目已存在",
        "LANG_FILTERLEVEL_IS_HIGH": "防火墙等级为高时，端口过滤不可配置",
        "LANG_LOGIN_PRIVILEGE": "登录权限",
        "LANG_MASK": "掩码",
        "LANG_IP_QOS": "IP QoS",
        "LANG_TOTAL_BANDWIDTH_LIMIT": "总带宽限制",
        "LANG_REMARK_ENABLE": "重标记启用开关",
        "LANG_REMARK_MODE": "重标记模式",
        "LANG_TRANSPARENT_MODE": "透传模式",
        "LANG_OVER_WRITE": "改写",
        "LANG_POLICY": "策略",
        "LANG_PRIO": "优先级策略",
        "LANG_QUEUE": "队列",
        "LANG_WRR": "权重策略",
        "LANG_QOS_CONFIG": "Qos 配置",
        "LANG_QOS_CLASSIFICATION": "QoS 分类",
        "LANG_TOTAL_WRR_LIMIT": "WRR 策略权重之总合必需为 100",
        "LANG_MARK": "标记",
        "LANG_CONNECT_TYPE": "连线类型",
        "LANG_VERSION": "版本",
        "LANG_ADD_IP_QOS_TRAFFIC": "增加网络流量控制类型规则",
        "LANG_FLOW_CONTROL_TYPE_NAME": "流量控制类型名",
        "LANG_IP_PROTOCOL_VERSION": "IP 协议版本",
        "LANG_FILTER_ADD_ERROR_15": "请指定 IP 协议版本",
        "LANG_NET_QOS_CLS_PAGE_5": "指定 IP 优先次序标记",
        "LANG_NET_QOS_CLS_PAGE_6": "指定差分服务代码点（DSCP）标记",
        "LANG_NET_QOS_CLS_PAGE_7": "如果 WAN 口 802.1p 被启用，则设置 802.1p 值",
        "LANG_MODE_SELECTION": "模式选择",
        "LANG_GENERAL_MODE": "一般模式",
        "LANG_APPLICATION_TYPE": "应用类型",
        "LANG_PHYSICAL_LAN_PORT": "物理局域网端口",
        "LANG_DSCP_CHECK": "差分服务代码点（DSCP）核对",
        "LANG_8021P_PROORITY": "802.1p 优先级",
        "LANG_SOURCE_IP_ADDRESS": "源IP地址",
        "LANG_SOURCE_SUBNET_MASK": "源子网掩码",
        "LANG_DESTINATION_IP_ADDRESS_TITLE": "目的 IP 地址",
        "LANG_DESTINATION_SUBNET_MASK": "目的子网掩码",
        "LANG_SOURCE_PREFIX_LENGTH_TITILE": "源前辍长度",
        "LANG_DESTINATION_PREFIX_LENGTH_TITILE": "目的前辍长度",
        "LANG_SOURCE_PORT_TITLE": "源端口（端口/端口:端口）",
        "LANG_DESTINATION_PORT_TITLE": "目的端口（端口/端口:端口）",
        "LANG_SOURCE_MAC_TITLE": "源MAC地址（xx:xx:xx:xx:xx:xx）",
        "LANG_DESTINATION_MAC_TITLE": "目的MAC地址（xx:xx:xx:xx:xx:xx）",
        "LANG_PAGE_DESC_CLASSICY_QOS_RULE_EXTRA": "在新增规则后，请按钮选择“应用”来启用",
        "LANG_NET_QOS_CLS_ERROR_1": "流量控制类型名包含非法字符，请重新填写！",
        "LANG_NET_QOS_CLS_ERROR_2": "请选择 IP 优先次序标记！",
        "LANG_NET_QOS_CLS_ERROR_3": "必须配置至少一个流量控制条件！",
        "LANG_NET_QOS_CLS_ERROR_4": "源 IP 地址输入非法",
        "LANG_NET_QOS_CLS_ERROR_5": "源子网掩码格式非法！",
        "LANG_NET_QOS_CLS_ERROR_6": "目的 IP 地址输入非法",
        "LANG_INVALID_SOURCE_IPV6_ADDRESS": "无效的源 IPv6 地址！",
        "LANG_NET_QOS_CLS_ERROR_7": "不正确的 IPv6 前缀长度",
        "LANG_NET_QOS_CLS_ERROR_8": "不正确的 IPv6 目的 IP 地址",
        "LANG_NET_QOS_CLS_ERROR_9": "不正确的 IPv6 目的前辍长度",
        "LANG_NET_QOS_CLS_ERROR_10": "目的子网掩码格式非法",
        "LANG_NET_QOS_CLS_ERROR_11": "源起始端口非法",
        "LANG_NET_QOS_CLS_ERROR_12": "协议不是 TCP/UDP，无法指定端口",
        "LANG_NET_QOS_CLS_ERROR_13": "源结束端口非法",
        "LANG_NET_QOS_CLS_ERROR_14": "目的起始端口非法",
        "LANG_NET_QOS_CLS_ERROR_15": "目的结束端口非法",
        "LANG_NET_QOS_CLS_ERROR_16": "源 MAC 地址输入非法",
        "LANG_NET_QOS_CLS_ERROR_17": "目的 MAC 地址输入非法",
        "LANG_INVALID_DESTINATION_VALUE": "无效的目标值。",
        "LANG_TRAFFIC_CONTROL": "流量控制",
        "LANG_RATE": "速率",
        "LANG_DIRECTION": "方向",
        "LANG_RATE_LIMIT": "速率限制",
        "LANG_DOWNSTREAM": "下行流",
        "LANG_WAN_INTERFACE_NOT_ASSIGNED": "未分配的 WAN 接口！",
        "LANG_SOURCE_IP_INVALID": "源 IP 无效！",
        "LANG_DESTINATION_IP_INVALID": "目标 IP 无效",
        "LANG_SOURCE_IP_MASK_INVALID": "源 IP 掩码无效",
        "LANG_DESTINATION_IP_MASK_INVALID": "目标 IP 掩码无效",
        "LANG_SOURCE_PORT_INVALID": "源端口无效",
        "LANG_PLEASE_ASSIGN_TCP_UDP": "请指定 TCP/UDP！",
        "LANG_DESTINATION_PORT_INVALID": "目标端口无效",
        "LANG_UPLINK_RATE_INVALID": "uplink rate 无效",
        "LANG_INVALID_DESTINATION_IPV6_ADDRESS": "无效目标 IPv6 地址！",
        "LANG_THE_RATE_MUST_MULTIPLE_OF_FOT": "速率必须是 512 的倍数",
        "LANG_SOURCE_MASK": "来源掩码",
        "LANG_DESTINATION_MASK": "目的掩码",
        "LANG_SOURCE_PREFIX_LENGTH": "来源端前置长度",
        "LANG_DESTINATION_PREFIX_LENGTH": "目的端前置长度",
        "LANG_MGM_USER_PASSWORD_RULE0": "您当前的登陆使用了默认密码，根据设备安全规则，要求您重新设置与默认密码不一样的密码。",
        "LANG_WARNING_WRONG_PASSWORD": "错误：密码错误！",
        "LANG_NEXT_STEP": "下一步",
        "LANG_BACK": "返回",
        "LANG_QUICK_GUIDE": "快速引导",
        "LANG_QUICK_GUIDE_TIPS1": "如果您不知道 PPPoE 账号和密码，请联系本地 Internet 服务提供商。",
        "LANG_QUICK_GUIDE_TIPS2": "如果您正通过 WLAN 访问该页面，应用后请手动刷新页面",
        "IPv6 WAN Info": "IPv6 WAN 信息",
        "IPv6 Network Info": "IPv6 网络信息",
        "LANG_PARAMETER": "参数",
        "LANG_CONNECTED": "已连接",
        "LANG_NOT_CONNECTED": "未连接",
        "LANG_NOT_SUPPORT": "不支持",
        "LANG_USB_PARTITION_SELECTION": "USB 分区选择",
        "LANG_CONFIG_RECOVERY": "配置快速恢复",
        "LANG_SAVE_FAILED": "保存失败",
        "LANG_BACKUP_CONFIGRUTION": "备份配置",
        "LANG_USB_UNLOAD": "USB卸载",
        "LANG_BACKUP_IS_EXIST": "配置文件备份已存在！",
        "LANG_BACKUP_AFTER_DELETE": "删除后备份",
        "LANG_NOT_ENOUGH_SPACE": "空间不够",
        "LANG_SAVE_SUCCESSFULLY": "保存成功",
        "LANG_UNLOAD_SUCCESSFULLY": "卸载成功",
        "LANG_UNLOAD_FAILED": "卸载失败",
        "LANG_USB_FILE_DIRECTORY": "USB 远程下载文件存放目录",
        "LANG_REMOTE_URL": "远程URL",
        "LANG_STORAGE_NOTE_1": "URL格式：[协议]://[主机名]/[文件路径]/[文件名]，协议支持 HTTP/FTP",
        "LANG_DOWNLOAD": "下载",
        "LANG_APP_STORAGE_ERR_3": "请输入合法的端口号！",
        "LANG_APP_STORAGE_ERR_4": "请输入合法的远程 FTP URL！",
        "LANG_USBP_DEVICE_MAKE": "制造商",
        "LANG_USBP_MGM": "USB 打印机",
        "LANG_STORAGE": "家庭存储",
        "LANG_DOWNLOAD_FAIL": "下载失败！",
        "LANG_EDIT": "编辑",
        "LANG_OTHER_MANAGEMENT": "更多管理",
        "LANG_WAN_MODE": "上行方式",
        "LANG_WAN_MODE_AUTO": "PON 自动切换",
        "LANG_WAN_MODE_NOTE": "切换上行方式后，设备将自动重启！",
        "LANG_PPPOE_INFO": "PPPOE 信息",
        "LANG_PPPOE_ACNAME": "AC 名称",
        "LANG_UPNP_ERR_1": "错误：WAN接口不能为空",
		    "LANG_TO":" 总共",
		    "LANG_PER_PAGE":" 行每页",
        "LANG_PLDT_PASSWORD_RULE0": "密码长度至少为8个字符。",
        "LANG_PLDT_PASSWORD_RULE1": "密码必须输入最多15个字符。",
        "LANG_PLDT_PASSWORD_RULE2": "密码至少包含以下3种字符的组合:",
        "LANG_STUN_CONFIG": "STUN 配置",
        "LANG_STUN": "STUN",
        "LANG_SERVER_PORT": "服务器端口",
        "LANG_SIGNAL_STRENGTH": "信号（dBm）",
        "LANG_DETECT": "检测",
        "LANG_AP_DETECT_ERROR": "请启用 WLAN 以进行 AP 扫描！",
        "LANG_AP_DETECT": "AP 检测",
        "LANG_IPERF_TEST": "Iperf 测试",
        "LANG_USB_BACKUP_CONFIG_RESTORE_AND_REBOOT": "USB备份配置恢复且重启",
        "LANG_USB_BACKUP_CONFIG_RESTORE_SUCCESS": "USB备份配置恢复成功",
        "LANG_USB_BACKUP_CONFIG_RESTORE_ERR1": "恢复失败：请先启用配置快速恢复功能。",
        "LANG_USB_BACKUP_CONFIG_RESTORE_ERR2": "恢复失败：没有找到备份的配置文件，请先备份配置。",
        "LANG_USB_BACKUP_CONFIG_RESTORE_ERR3": "恢复失败。",
    }
}

$(document).ready(function () {
    $(".lang").each(function (index, element) {
        $(this).text(arrLang["zh"][$(this).attr("key")]);
    });
    $("#ajax_load_file").prop("src", "js/" + $(".title_flag").attr("flag") + "_control.js");
});
